mozilla/DeepSpeech

DeepSpeech.ipynb
Several small changes in prep for [CTC integration](https://github.com/mozilla/DeepSpeech/milestone/1), [Adam optimizer integration](https://www.tensorflow.org/versions/r0.10/api_docs/python/train.html#AdamOptimizer), [TED-LIUM integration](https://github.com/mozilla/DeepSpeech/milestone/4)…
- General cleaning
- Change text to refer to [MFCC](https://en.wikipedia.org/wiki/Mel-frequency_cepstrum) features
- Made placeholder `y` of proper type for CTC
- Removed `istate_fw` and `istate_bw` as, for now, we don’t use them
=> Prep for milestones 1 and 4

DeepSpeech.ipynb
The documentation is unclear, so I tested this on the ldc set by changing the 'year' in sentence to 'lear', so it included the sequence 'all lear' (which has a repeated character, then a space, then the same character - which I wanted to verify also). I was able to over-fit and produce the correct result.
=> Don't merge repeated characters in ctc_beam_search_decoder, fixes #53

util/audio.py
Experimental PR - on ldc93s1 it reduced time by factor 2 AND converged faster (approximately 1.5 times - why?).
We now have to see how this performs on real/big data.
=> Fix #284; BiRNN with stride 2

native_client/BUILD, native_client/Makefile, native_client/README.md
Build separate libraries for kissfft, c_speech_features and libdeepspeech.
This allows us to specify c99 for c_speech_features and should fix
issue #441.
=> Separate libdeepspeech/c_speech_features/kissfft library builds

DeepSpeech.py, demos/deepspeech_demos.py, requirements.txt, util/audio.py, util/automation.py, util/importers/LDC97S62.py, util/importers/fisher.py, util/importers/ldc93s1.py, util/importers/librivox.py, util/importers/ted.py, util/shared_lib.py, util/spell.py, util/text.py, util/website.py
These are just mechanical/trivial changes to enable the first demo (ldc93s1) to run to completion under Python 3.6 (on Linux) as I wanted to see how it ran.
In theory we could do something smarter with the git revision and branch extraction, as currently we use a latin-1 decode (rather than the system native encoding) to get them to unicode form. Most of the rest of the changes are using modern prints and do a few list() calls around things that produce iterators under Python 3.x
=> Allow for running under Python 3.6

native_client/BUILD
On my desktop, makes a `bazel build -c opt [...] //native_client:*`
after a `bazel clean` running in ~150 secs instead of 560 secs.
Fixes #475
=> Limit libdeepspeech -> tensorflow deps

util/data_set_helpers.py
`util/data_set_helpers.py` `SwitchableDataSet.__init__`'s line:
`self._queues = [s._example_queue for s in self._sets]` seems to mean `.example_queue`, since that's what is defined in every importer.
Culprit traceback before this patch:
``` bash
[mike@self DeepSpeech] $ ./bin/run-ldc93s1.sh 
+ '[' '!' -f DeepSpeech.py ']'
+ python -u DeepSpeech.py --importer ldc93s1 --train_batch_size 1 --dev_batch_size 1 --test_batch_size 1 --n_hidden 494 --epoch 50
Traceback (most recent call last):
File "DeepSpeech.py", line 1646, in <module>
tf.app.run()
File "/home/mike/projects/rnn/DeepSpeech/env/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "DeepSpeech.py", line 1609, in main
train()
File "DeepSpeech.py", line …
```
=> Fix _example_queue in data_set_helpers to be example_queue as named in the importers

bin/run-ted.sh
`bin/run-ted.sh` was referring to `/data/LIUM`, when what it means is `data/LIUM`.
=> make run-ted.sh store to data instead of /data

bin/import_fisher.py, bin/import_ldc93s1.py, bin/import_librivox.py, bin/import_swb.py, bin/import_ted.py
This prevents weirdness when invoking DeepSpeech.py from a different folder than you ran the bin/import_* scripts.
=> Save absolute paths in dataset definition files

bin/import_ted.py
This lets us re-run the importer to re-create the CSV files, if we want to include punctuation or accents, for example. The downside is using more disk space than it's strictly necessary.
=> Keep unsplit WAV files in the TED corpus

native_client/Makefile
strip triggers issues on OSX:
/Library/Developer/CommandLineTools/usr/bin/strip: symbols referenced by
indirect symbol table entries that can't be stripped in:
/usr/local/lib/libtensorflow.so
Let's disable strip on install, we can always hand-strip if it is really
useful.
Fixes #635
=> Avoid stripping during install

util/audio.py
This is about 30% faster than the old code (35% if we didn't have to copy the strided array for whitening), and cleaner too, IMO.
=> Improve the Python audioToInputVector implementation

util/feeding.py
There was a small bug in feeding.py where i got
`NameError: global name 'files' is not defined`
when running run-librivox.sh
=> fix bug in feeding.py

bin/import_timit.py, bin/run-timit.sh
Hi,
I created a TIMIT preparation script for everything (excluding the download, as it's LDC). It was one of the few, very well used, paid LDC datasets that I had at my disposal. It's only small, with around 5 hours worth of audio and has 630 speakers with 10 types of specially crafted sentences, designed to test ASR systems. 
"The TIMIT corpus of read speech is designed to provide speech data for acoustic-phonetic studies and for the development and evaluation of automatic speech recognition systems. TIMIT contains broadband recordings of 630 speakers of eight major dialects of American English, each reading ten phonetically rich sentences. The TIMIT corpus includes time-aligned orthographic, phonetic and word transcriptions as well as a 16-bit, 16kHz speech waveform file for each …
=> Import TIMIT dataset

DeepSpeech.py, util/text.py
We can either check if we're running on Python 2 or 3 every time we call `str` (so that we can call `unicode` instead on Python 3, or just avoid calling either one. This doesn't fix some obscure cases like non-ASCII characters in exception messages, but it works on both Python 2 and 3, with and without non-ASCII characters in the alphabet and training data.
=> Fix handling of Unicode messages when using custom alphabets (Fixes #849)

util/tc.py
Native_client file is in .tar.xz format so extracting with tar -xzvf will give error "gzip: stdin: not in gzip format"
=> Fix gzip format error to uncompress tar.xz via tc.py

taskcluster/darwin-opt-base.tyml, taskcluster/linux-opt-base.tyml, taskcluster/test-linux-opt-base.tyml
Generated with:
$ sed -ri 's|runs/0/||g' taskcluster/*.tyml
Fixes #933
=> Remove 'runs/0' references in artifacts path

DeepSpeech.py, util/audio.py
This makes sure DeepSpeech.py is usable for running test epochs on an externally obtained checkpoint without changing its state, and also a one-shot inference mode that takes in an audio path and does inference on it (again, based on the checkpoint).
The commit moving the deprecation warning to stderr is just so that the only stdout output in one-shot mode is the inference result itself.
Initially I tried hooking into the existing training setup by creating a new "one-shot" type of `Job` and using that with the coordinator, but that only lead to frustration debugging a thousand problems. Since all of that code is changing soon anyway, I decided to put this code on an earlier level of the execution, next to `train()` and `export()`.
=> Add one shot inference mode and make sure test-only runs don't change the checkpoint state

data/lm/lm.binary
This reverts commit c5db7d1f71556e63805c3ab57a4b6baa3b8ca294 and fixed #965
=> Revert "Added language model with apostrophe"

README.md
Fixes #993 however, merge should wait until we've gotten PyPI to increase the limit of deepspeech-gpu
=> Fixed #993

README.md
Trivial, fixes typo in Installing DeepSpeech Python bindings block.
=> Fixes typo in Installing Python bindings block

README.md
When installing DeepSpeech, I didn't notice the version of python (which is listed only once in the dependencies section). I went straight to setting up a virtualenv, and the process for doing so is different on Python 2 vs Python 3. So I suggest mentioning the python version when virtualenv is first mentioned.
Also, on Debian-derived systems there is a package `git-lfs` which makes it unnecessary to install Git Large File System manually.
=> README.md Suggestions

README.md
This change aligns command line examples with the content of provided pre-traned models and allows to run it out of box.
=> [Docs] Renames output_model.pb to output_graph.pb in README

util/taskcluster.py
Create target dir if not exists to prevent downloading error
=> taskcluster.py: create target dir if not exists

DeepSpeech.py
Fixes https://github.com/mozilla/DeepSpeech/issues/1140. Separated this commit from https://github.com/mozilla/DeepSpeech/pull/1132#discussion_r159027991 as following the feedback.
=> Fix FLAGS.remove_export not working

DeepSpeech.py
Fixes https://github.com/mozilla/DeepSpeech/issues/1016
Steps to reproduce the bug:
```shell
mkdir models
./bin/run-ldc93s1.sh --decoder_library_path decode/libctc_decoder_with_kenlm.so --export_dir models
./bin/run-ldc93s1.sh --decoder_library_path decode/libctc_decoder_with_kenlm.so --export_dir models
...skip...
Traceback (most recent call last):
File "DeepSpeech.py", line 1830, in <module>
tf.app.run()
File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
_sys.exit(main(_sys.argv[:1] + flags_passthrough))
File "DeepSpeech.py", line 1821, in main
export()
File "DeepSpeech.py", line 1747, in export
log_error(sys.exc_info()[1])
File "DeepSpeech.py", line 349, in log_error
prefix_print('E ', message)
File "DeepSpeech.py", line 329, in …
```
=> Pass string rather than exception object to log_error()

DeepSpeech.py
This should fix the regression from 18b4120f302131a6653b589696db507382f0b050.
@kdavis-mozilla can you test this with the checkpoint to see if the results make more sense? Thanks.
=> Compute edit distance on word level

DeepSpeech.py
This flag allows one to resume training from a frozen model, but as documented on the flag, it does not restore optimizer parameters, so adjusting the learning rate is necessary. I think it's an OK requirement from users.
=> Initialize training from frozen model

native_client/python/model.i
Without this, `model.stt` will hold the GIL and block Python code in other threads.
=> Enable SWIG threads support in model.i

DeepSpeech.py
As of TF 1.5, you can't access tf.app.flags before `tf.app.run` is called.
=> Move decoder module initialization to initialize_globals

README.md
This adds a link in the README to the gst-deepspeech project which provides a GStreamer element that wraps DeepSpeech and performs basic audio segmentation, making it usable for continuous dictation within a multimedia pipeline.
=> Add a link to the gst-deepspeech GStreamer plugin

native_client/python/client.py
If the wav file is not 16 kHz, conversion is done using SoX via a subprocess. The converted file is saved in a temporary folder and deleted after execution. #1022 Tested on Ubuntu 16.04
=> Transcode input audio to 16 kHz #1022

requirements.txt
When attempting to do local model training I noticed I had to manually install the "requests" package.  This should address that issue.
=> Fixed missing "requests" package

README.md
This is a new attempt to update the README, sorry for the "pull noise". Now it only has one commit, and is being merged from a branch. See #1301 (which can now be deleted) and issue #1298.
=> Update README to use python3 only

bin/benchmark_nc.py, bin/benchmark_plotter.py, native_client/python/client.py, util/taskcluster.py
When no `type` keyword argument is passed to the `add_argument` method of an `argparse.ArgumentParser`, the type will be `str` by default and therefore this does not need to be specified.
=> Remove keyword argument that has default value

Dockerfile
Dockerfile: added --copt=-D_GLIBCXX_USE_CXX11_ABI=0 flag to TF pip package compilation to fix missing _ZN10tensorflow8internal21CheckOpMessageBuilder9NewStringEv symbol error
=> Dockerfile: --copt=-D_GLIBCXX_USE_CXX11_ABI=0 flag in all builds

DeepSpeech.py
We condition logging of summaries on `FLAGS.summary_secs > 0`, since the full logging of variables and gradients is expensive.
Logging of step losses is cheap and useful, so there's no need to avoid logging it.
This is what it looks like in TensorBoard when run with LDC93S1:
=> Log step avg loss unconditionally

DeepSpeech.py
There are multiple paths that could lead to trying to read `update_progressbar.pbar` without ever calling `update_progressbar()`, but they already check for `None`.
=> Fix errors with uninitialized update_progressbar() field

bin/import_ts.py
Aims to generate english-complatible dataset since no FR alphabet.txt available right now.
See https://github.com/mozilla/DeepSpeech/pull/1599#issuecomment-426544379 for more info
usage:
```shell
$ ./bin/import_ts.py  --help
usage: import_ts.py [-h] [--english-compatible] target_dir
Importer for TrainingSpeech dataset.
positional arguments:
target_dir
optional arguments:
-h, --help            show this help message and exit
--english-compatible  Remove diactrics and other non-ascii chars.
```
remaining chars:
```shell
$ tail -n +2 -q  /tmp/ts_*.csv | gawk -F "," '{print $3}' | tr '\n' ' ' | awk -F "" '{for (i=1; i<=NF; i++) print $i}' | sort | uniq |sort
'
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
```
=> [TrainingSpeech importer] generate english-complatible dataset

README.md
In the making mmap-able model part of the REAMDE.md file, there is no mention of providing `convert_graphdef_memmapped_format` as the artifact name for `taskcluster.py` file. Without this argument `taskcluster.py` file tries to download the default `native_client.tar.xz` artifact and the code receives a 404 error.
=> Updated making mmap-able model part of README.md

bin/import_ts.py
`2018-11-24_fr_FR` fixes many annotation issues (~500) such as empty audio etc.
@lissyx could you please take a look ?
=> use TrainingSpeech release 2018-11-24_fr_FR

README.md
PR: #1762: Update README.md To get a command line options, Should be --helpfull not --help
=> #1762: Update README.md To get a command line options, Should be --helpfull not --help 

examples/ffmpeg_vad_streaming/index.js, examples/mic_vad_streaming/README.md, examples/mic_vad_streaming/mic_vad_streaming.py, examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs, examples/net_framework/CSharpExamples/DeepSpeechWPF/MainWindow.xaml.cs, examples/vad_transcriber/wavTranscriber.py, native_client/client.cc, native_client/java/app/src/main/java/deepspeech/mozilla/org/deepspeech/DeepSpeechActivity.java, native_client/java/app/src/main/java/deepspeech/mozilla/org/deepspeech/Model.java, native_client/javascript/client.js, native_client/python/client.py, tc-tests-utils.sh, util/flags.py
I'm gonna give it another try at embedding hyperparams in our models, as this PR should *really* not be this big.
Raw data from the runs is attached. Best results were with alpha=0.75, beta=1.85.
[runs_3311_3206.csv.txt](https://github.com/mozilla/DeepSpeech/files/2715602/runs_3311_3206.csv.txt)
[runs_3296_3273.csv.txt](https://github.com/mozilla/DeepSpeech/files/2715603/runs_3296_3273.csv.txt)
[runs_3295_3206.csv.txt](https://github.com/mozilla/DeepSpeech/files/2715604/runs_3295_3206.csv.txt)
=> Update decoder hyperparameters

.github/lock.yml
This config enables the [lock app](https://github.com/apps/lock) to lock inactive issues/PRs after they're closed an inactive for 30 days, hopefully helping to avoid necromancing of old threads in the repo. I'll ask for review after the holidays just to get approval from everyone.
=> Add lock bot config

native_client/java/Makefile, native_client/java/libdeepspeech/build.gradle, taskcluster/android-apk-package.sh, taskcluster/scriptworker-task-github.yml, taskcluster/scriptworker-task-jcenter.yml, taskcluster/scriptworker-task-pypi.yml, taskcluster/simple-task.tyml, tc-tests-utils.sh
=> Produce Maven Bundle

evaluate.py, evaluate_tflite.py, requirements_eval_tflite.txt, util/evaluate_tools.py
=> Add TFLite accuracy estimation tool

util/text.py
This PR merely removes `\n` from the error message in `text.py`. Also, the message is shortened.
=> Prettier error message to the terminal when alphabets are mis-matched.

util/check_characters.py
`--alphabet-format` flag will print found alphabet to terminal and can be copy-pasted into `alphabet.txt`
Also now script makes use of `argparse`.
=>  --alphabet-format flag

.compute
This should fix any pip/pip3, python/python3 executable naming issues and work consistently in developer machines as well as the cluster.
=> Use venv module in .compute script

DeepSpeech.py
NB: for now `export_batch_size` must be greater than or equal to 1 due to https://github.com/mozilla/DeepSpeech/blame/master/DeepSpeech.py#L672 and https://github.com/mozilla/DeepSpeech/blame/master/DeepSpeech.py#L703
It would be nice to enable dynamic `batch_size` but outside the scope of this PR
BTW, 
flag `export_batch_size` was already there but was not used. see https://github.com/mozilla/DeepSpeech/blame/master/util/flags.py#L65
=> allow custom export_batch_size (see #1920)

README.md, examples/nodejs_wav/Readme.md, examples/nodejs_wav/index.js, examples/nodejs_wav/package.json
Added a simple example using NodeJS bindings, single script, single wav file.
=> add simple nodejs example

util/check_characters.py
When reading in a CSV, this script (in error) has been reading in the characters from the header.
For English and most Roman alphabet languages, this isn't noticed, but for non-Roman alphabets we end up adding the unique letters of the column header `transcript` into the alphabet.
This small fix just skips over the header.
=> skip file header of CSV file when reading alphabet

bin/run-ldc93s1.sh
The main use of bin/run-ldc93s1.sh is to test our code, not any training aspect, so I propose we make it faster to speed-up edit-test cycles. With these changes I can run it in 5 seconds on my laptop CPU, which is pretty good.
=> Make bin/run-ldc93s1.sh run faster

tc-tests-utils.sh
Add .NET framework targets to the Nuget package, adding .NET Frameworks client for 4.5,4.6 and 4.7, not ready yet, maybe will include the fix for the .so not being moved to the target directory.
=> Add NET Framework targets

native_client/args.h, native_client/client.cc, native_client/deepspeech.cc, native_client/deepspeech.h
Letter timings are exposed on the API and the client then converts these into word-level timings. The client outputs CSV when used with the -e command-line argument.
=> Output word timings

DeepSpeech.py, README.md, bin/run-ldc93s1.sh, bin/run-tc-ldc93s1_checkpoint.sh, bin/run-tc-ldc93s1_new.sh, bin/run-tc-ldc93s1_singleshotinference.sh, util/flags.py
This PR removes the epoch calculation logic when restoring checkpoints, and makes the `--epoch` flag always be relative. This avoids problems when fine tuning or transfer learning and makes it easier to think about how much training was done on a model, just look at the global step.
The tf.data input pipeline has the ability to be saved inside the checkpoint with the rest of the graph, which we can leverage to properly resume training runs stopped half way through an epoch, but it needs to be tested thoroughly.
=> Ignore epochs in checkpoints, always start epoch count from zero

native_client/definitions.mk, native_client/python/Makefile, native_client/python/__init__.py, taskcluster/.shared.yml, taskcluster/test-nodejs_10x-win-amd64-opt.yml, taskcluster/test-nodejs_11x-win-amd64-opt.yml, taskcluster/test-nodejs_4x-win-amd64-opt.yml, taskcluster/test-nodejs_6x-win-amd64-opt.yml, taskcluster/test-nodejs_7x-win-amd64-opt.yml, taskcluster/test-nodejs_8x-win-amd64-opt.yml, taskcluster/test-nodejs_9x-win-amd64-opt.yml, taskcluster/test-python_35-win-amd64-opt.yml, taskcluster/test-python_36-win-amd64-opt.yml, taskcluster/test-python_37-win-amd64-opt.yml, taskcluster/win-build.sh, taskcluster/win-package.sh, tc-python-tests-prod.sh, tc-python-tests.sh, tc-single-shot-inference.sh, tc-tests-utils.sh
=> Windows Python bindings

native_client/ctcdecode/third_party/openfst-1.6.7/src/include/fst/symbol-table.h
When building with clang the following compilation error is thrown:
symbol-table.h:199:3: error: no template named 'map'
map<int64, int64> key_map_;
^
This patch solves that issue by explicitly specifying the std namespace.
=> Use std::map to fix compilation issue with clang

native_client/client.cc
I spotted a bug in the WordsFromMetadata function in the client. It should be "if it's not a space AND if it's not a UTF8 space", otherwise you still get the space appended to the word.
=> Fix spaces being appended to word

DeepSpeech.py, bin/run-tc-ldc93s1_new.sh, evaluate.py, util/feeding.py, util/flags.py, util/logging.py
As a consequence this also removes support for caching to disk the processed validation and test sets. They're usually small enough that caching to disk makes very little difference, and the complexity of keeping track of multiple cache paths for each CSV is not worth it IMO.
Sorry for the continued churn on the progress bar/logging part of the code. This PR also includes some cleanup of that code using `progressbar.NullBar` so that there's now a single check for the `--show_progressbar` flag. With this PR, the log with and without progress bars should be consistent in the information it provides.
I recommend disabling whitespace changes for reviewing the last commit that touches `evaluate.py`, otherwise the diff ends up looking like a mess.
=> Perform separate validation and test epochs per dataset when multiple files are specified (Fixes #1634 and #2043)

native_client/README.md, native_client/javascript/client.js, native_client/javascript/deepspeech.i, native_client/javascript/index.js, native_client/python/client.py, native_client/python/impl.i, native_client/python/setup.cfg, native_client/python/setup.py
v8 does not guarantee wrapper destructors will get called, so we need to expose and use the DS_DestroyModel/DS_FreeMetadata functions. DS_FreeString can be handled by the SWIG layer because the contents are copied into the v8 object.
On the Python bindings I made the Metadata.items array look like a list on the Python side and cleaned up linter errors in setup.py.
=> Some bindings clean-up

native_client/ctcdecode/ctc_beam_search_decoder.cpp, native_client/ctcdecode/ctc_beam_search_decoder.h, native_client/ctcdecode/decoderstate.h, native_client/deepspeech.cc
Refactored the CTC decoder to work with streaming data.
=> CTC streaming decoder

native_client/dotnet/DeepSpeechConsole/Program.cs
Related to different transcriptions between platforms.
https://discourse.mozilla.org/t/compiling-the-0-4-1-client-on-windows/38345/5
=> Change wrong BEAM_WIDTH .NET console client

taskcluster/darwin-opt-base.tyml, taskcluster/test-darwin-opt-base.tyml
It seems like `-e` does is job and bash catches faulty exit code, thus
avoiding the required `mv` for dealing with caches. Doing it in a second
command should help
=> Ensure proper cleanup on macOS workers

bin/import_cv2.py
Most of languages are phonogram, but mandarin are logogram.
For example, in English you can, more-or-less split on spaces to get words. However, for Chinese Mandarin each character is a word. So Mandarin transcripts should be split by spaces.
=> common voice mandarin import problem

evaluate_tflite.py
Save the output for future use (e.g. calculate WER directly without running STT again).
And print the current progress.
Signed-off-by: Li Li <eggonlea@msn.com>
=> dump output when evaulating

util/flags.py
This adds a check to make sure files exist using abseil for some of the command line flags. See issue in  #1954.
=> add validators for command line arguments that require paths

native_client/test/concurrent_streams.py, taskcluster/tc-tests-utils.sh, taskcluster/test-armbian-opt-base.tyml, taskcluster/test-darwin-opt-base.tyml, taskcluster/test-linux-opt-base.tyml, taskcluster/test-raspbian-opt-base.tyml, taskcluster/test-win-opt-base.tyml
This is just the checkpoint from 0.5.0 re-exported with the code from 0.6.0-alpha.0 since we changed the inference graph in #2184
=> Update prod tests to point to re-exported 0.5 model

util/text.py
I noticed when checking some of the files in the Common Voice dataset that there were situations like the following:
> Expected transcript: beall and the endall
> Actual transcript: be all and the end all
DeepSpeech actually got the transcription perfect, but it's still counted as inaccurate because the importer script stripped out the hyphen separating those words.
It also seems to cause issues with numbers, with `nineteen-sixty-nine` becoming `nineteensixtynine`.
This PR replaces hyphens with spaces and adds a regex for safety to strip out any double spaces that may occur as a result.
=> Label validation - Replace hyphens with spaces

util/feeding.py, util/text.py
This way we can get a plain English exception early, rather than a matrix shape error during training.
=> Checking for empty transcripts during character encoding

native_client/ctcdecode/ctc_beam_search_decoder.cpp, native_client/ctcdecode/path_trie.cpp
The intention of this check is to improve the accuracy of the timings by recording the time step where the character saw its highest probability rather than the first time step where it was seen. The problem happens when updating the time step of a prefix that already has children. In that case, if any of the children have a time step that is earlier than `new_timestep`, it'll break the linearity of the timings. My fix is to simply check that the prefix we're updating is a leaf.
For example, say during decoding we have the following beams (format is `(char | time)`, tree node id below, nodes with same id are the same object):
```
1. (-1 | 0 ) -> ('s' | 10) -> ('h' | 13) -> ('e' | 14)
A             B             C             D
2. (-1 | 0 ) -> ('s' | 10) -> ('h' | 14)
A             B …
```
=> Only update time step of leaf prefixes (Fixes #2294)

taskcluster/tc-tests-utils.sh, taskcluster/win-build.sh
We need to build the WPF example to check any inconsistency with the client. Introduced the usage of `/t:Rebuild` to clean/build always and avoid any weird behavior from cached files.
=> Add WPF example build

util/feeding.py
With the new `create_dataset` approach introduced by PR #2283 (read: mine, sorry!), duplicate
indices in the df would cause a fatal error where the columns could not be referenced by
name. Adding `ignore_index=True` during append allows pandas to assign new indices to
rows, and fixes the issue.
=> Fixed issue where multiple csvs could not load

native_client/deepspeech.h
Currently it is not possible to use `deepspeech.h` in a project written in C, since there are compilation errors related to the use of `extern "C"` and missing struct keywords/typedefs.
With the following changes, I am able to use `native_client` in both C and C++ projects:
- Wrap the header in `extern "C"`, only when compiling as C++.
- Use `typedef` for structs so that they can be used without the `struct` tag.
I also removed trailing whitespace from the header.  I can rebase out that change if needed.
=> C compatibility

DeepSpeech.py
In my tests this fixes the discrepancy between results with and without CudnnRNN. Tilman, can you verify this does the right thing for you too?
=> Set forget_bias=0 in CPU graph for compatibility with CudnnRNN

util/flags.py
This adds alias according to $deepspeech --lm --trie --alphabet
with DeepSpeech.py and evaluate.py that use other names for the same flags
=> added alias for trie,alphabet,lm_binary in util/flags to match module

util/feeding.py, util/text.py
This makes training startup about 3x faster in my Mandarin runs, with the biggest difference coming from the `DataFrame.apply` change. It seems `apply` with `result_type='broadcast'` causes Pandas to have to copy of the entire DataFrame. Since we only modify the transcript anyway, I made it so that `text_to_char_array` takes in a series but returns just the transcript and used `result_type='reduce'` instead.
=> Improve training startup time

native_client/ctcdecode/build_common.py, native_client/ctcdecode/setup.py
These files are much more likely to be edited by us, and having them in common.a slows downs the development hugely because we have to build all the third party libraries every time, even though they never change. This is a good compromise between fast automation builds and good development speed.
=> Remove first party code from common.a

data/lm/README.rst, data/lm/generate_lm.py, data/lm/lm.binary, data/lm/trie
This is a conservative change due to the lack of good validation sets to explore more significant changes with confidence (for now). Basically just filter words that happen one or two times in the dataset. The 500k number came from inspecting the counts, it's roughly half of the size of the original vocabulary (as can be seen by the 2x reduction in the trie file size). This does not significantly change the size of the LM itself. The main win should be to get rid of some of the rare stuff that's in the Librispeech vocab and can throw off the transcription.
@kdavis-mozilla we should validate this change with the models from your latest runs once they are done.
=> Filter LM by removing very rare words

README.rst
This will need to be changed/removed when we do a stable release, and then added again, which is a pain, but given the amount of confusion we've seen due to master docs diverging from stable, I think it's worth it. We could also wait until after 0.6.0 to merge this so we don't have to do this dance so soon.
=> Warn about master docs applying to master only

USING.rst
libpthread on Ubuntu (and presumably any other Debian or Debian derivatives) is in the libpthread-stubs0-dev package, it took me a bit of digging to find it. Best, Kathy
=> Update to specify which package libpthread is in

DeepSpeech.py, util/feeding.py, util/flags.py, util/sparse_image_warp.py, util/spectrogram_augmentations.py
Hi,
The PR refactor the `sparse_image_warp.py` to fit dynamic shape of spectrogram, and add `augmentation_sparse_warp` parameter to `flags.py`
Try add parameter in `run-ldc93s1.sh` to test the code:
`python -u DeepSpeech.py --noshow_progressbar  --train_files data/ldc93s1/ldc93s1.csv --test_files data/ldc93s1/ldc93s1.csv --train_batch_size 1 --test_batch_size 1 --n_hidden 100 --epochs 200 --checkpoint_dir "$checkpoint_dir" --augmentation_sparse_warp true "$@"`
And maybe we could add a wrapper in `feeding.py` or somewhere for exporting few spectrogram figures while training on augmentation, which should let us be more confident on augmenting data.
So far, I was only developing on jupyter notebook, but I couldn't review the augmented data while training.
=> [SpecAugment] Refactor sparse_image_warp for dynamic shape of spectrogram

README.rst
Based on the discussion here: https://discourse.mozilla.org/t/inference-with-model-different-than-16khz/43217/17 models for data different than 16kHz can be trained and used with client now.
=> Remove information about 16 kHz only support

doc/TRAINING.rst, util/taskcluster.py
I had this "command not found" problem and solved it with https://discourse.mozilla.org/t/how-to-create-a-mmap-able-model-from-the-output-graph-pb-file/28984/13?, so I'm adding it to the documentation.
=> Update TRAINING.rst  (mmap-able model)

DeepSpeech.py, util/flags.py
When training models i felt like an argument was missing to choose the name of the export model when done training.
use as:
```
python -u DeepSpeech.py --noshow_progressbar \
--train_files data/ldc93s1/ldc93s1.csv \
--test_files data/ldc93s1/ldc93s1.csv \
--train_batch_size 1 \
--test_batch_size 1 \
--n_hidden 200 \
--epochs 200 \
--export_name name_of_model \
```
if no arg is given it will just use output_graph as name
=> added an argument to choose the final export model name

evaluate.py, evaluate_tflite.py, util/evaluate_tools.py, util/flags.py
This is also correcting the error that the results with the highest WER instead of the lowest WER are printed.
=> Print best and worst results in a WER report.

util/audio.py
based on the small issue discussion
https://github.com/mozilla/DeepSpeech/issues/2752
I've moved the line to import `webrtcvad` into the `vad_split ` function
=> made the webrtcvad dependency optional

native_client/python/impl.i, native_client/python/setup.py
How it looks:
```python
In [1]: from deepspeech import Model
In [2]: import scipy.io.wavfile as wav
In [3]: rate, samples = wav.read('data/ldc93s1/LDC93S1_clipped.wav')
In [4]: m = Model('/Users/reubenmorais/Downloads/models/output_graph.pbmm')
TensorFlow: v1.15.0-22-gbd115ee104
DeepSpeech: v0.7.0-alpha.2-8-g1c69d93b
In [5]: md = m.sttWithMetadata(samples)
In [6]: md
Out[6]:
Metadata(confidence=7.3753743171691895, items=[
MetadataItem(character='s', timestep=0, start_time=0.0),
MetadataItem(character='h', timestep=1, start_time=0.019999999552965164),
MetadataItem(character='e', timestep=20, start_time=0.3999999761581421),
MetadataItem(character=' ', timestep=22, start_time=0.4399999976158142),
MetadataItem(character='h', timestep=25, start_time=0.5),
MetadataItem(character='a', …
```
=> Add a better __repr__ for Metadata objects in Python bindings

native_client/javascript/index.js, native_client/python/__init__.py
They're written as hexadecimals in the header so this makes it easier to lookup the error name. We should probably add a [strerror](https://linux.die.net/man/3/strerror)-like API as well.
=> Report error code as hexadecimal numbers for easier lookup

util/feeding.py
In PR #2688, we started specifying the upper frequency limit when computing Mfccs. This value was computed as half of the `--audio_sample_rate` value. Despite accepting a variable sample rate input for the Mfcc computation, the TensorFlow OP only takes a constant upper frequency limit, so we can't pass a dynamic value computed from each sample to the op.
This means we lost the ability to transparently train on data with multiple sample rates, unless we do something like always specify a very high frequency limit. This commit adds a warning message in case a training sample does not match the `--audio_sample_rate` flag.
=> Warn if --audio_sample_rate does not match training sample

util/checkpoints.py, util/flags.py
When using reduce_lr_on_plateau, the reduced learning rate is saved in the checkpoint. If you want to resume from the checkpoint at a higher learning rate (passed in by --learning_rate) then you can set this flag.
=> Add flag to force reinitialisation of learning rate after lr_plateau

native_client/deepspeech.cc, native_client/deepspeech.h
Implementation of an API to get textual descriptions of error codes.
Fixes #2773
=> added implementation of DS_ErrorCodeToErrorMessage

native_client/dotnet/DeepSpeechClient/DeepSpeech.cs, native_client/dotnet/DeepSpeechClient/NativeImp.cs, native_client/java/jni/deepspeech.i, native_client/javascript/deepspeech.i, native_client/javascript/index.js, native_client/python/__init__.py, native_client/python/impl.i
Exposing our `DS_ErrorCodeToErrorMessage` API to our tree bindings
Closes #2773
=> Exposing ErrorCode API in Tree bindings

util/flags.py
There was a typo in the flags and therefore in the --helpfull messages that I corrected here.
=> Corrected typo in flags

native_client/ctcdecode/Makefile, native_client/ctcdecode/build_archive.py, native_client/ctcdecode/setup.py
This supports to build ctc_decoder wheel package on Windows system.
The package enable us to train models on Windows system.
My environments:
- Windows 10
- Visual Studio 2015
- Python 3.6
- Swig 3.0.12
- MSYS2
Build steps:
```
cd native_client\ctcdecode
set path=C:\msys64\usr\bin;%path%
set path=C:\ProgramData\swigwin-3.0.12;%path%
make TARGET=host-win
```
=> Support building ctc_decoder wheel package on Windows system

data/lm/generate_package.py
https://discourse.mozilla.org/t/segmentation-fault-ctc-beam-search-decoder-batch-on-mac/56090/13
=> Error early in generate_package.py if no alphabet was specified and not using UTF-8 mode

native_client/python/client.py
Noticed that the python client reports an incorrect duration value if transcribing audio with sample rate != 16kHz. 
The getnframes() method counts the frames directly from the wav file, while the fs var is always set to the desired 16000 sample rate when it is passed back from the convert_samplerate function, so the duration calculation is incorrect. 
Wasn't sure if I should edit the convert_samplerate function directly or make 2 distinct vars, but I ultimately decided on making 2 vars, so that the convert_samplerate function returns the usual samplerate, audio_vector tuple.
=> Fixed sample rate logic in Python client

DeepSpeech.py, lm_optimizer.py
This is an addendum to PR #2783 which adds trial pruning to the language model hyperparameter optimiser, documented here: https://optuna.readthedocs.io/en/latest/tutorial/pruning.html
The idea is to break the model inference into multiple steps so that trials can be abandoned early if the results look unpromising. I assumed that the user supplied multiple csv to the `test_files` flag in `utils/flags.py` and split the work across those. The user probably has to provide around 10 files for the feature to be useful.
I had to modify the calls to `variable_scope` in `DeepSpeech.py` in order to reuse the model across the multiple trials when it already exists.
=> Add trial pruning to lm_optimizer.py

doc/TRAINING.rst
Fix minor typos in the TRAINING documentation augmentation section.
=> Fix documentation typos in section Augmentation

doc/USING.rst
I wanted to install the binary without cloning the entire repository (and thereby the required `util/taskcluster.py`) and was only able to find it pretty much by chance. I feel that adding this into the README could save people from a few headaches.
=> Documentation Suggestion: native_client can be found in the releases

data/lm/README.rst, data/lm/generate_package.py
Removed tristate class for better readability.
Also updated `--kenlm_bins` parameter to use path from docker container, that users don't have to search for the installation path.
=> Refactor generate_package.py

native_client/Makefile, native_client/definitions.mk
All of the brew installed dependencies have static libraries as well, but the macOS linker will always prefer a dynamic library if both exist under the same `-L/foo -lbar` resolution. The only way to force static linking is to include a full path to the static library. These changes basically reverse engineer the static library locations and then pass those to the linker.
=> Ugly, very ugly, incredibly ugly static linking of libsox on macOS

native_client/python/client.py
Method name should be `setBeamWidth`, not `setModelBeamWidth`.
=> Fix beam width setting in python client

training/deepspeech_training/evaluate.py
Removed spurious overwriting of argument 'test_csvs' in evaluate.py
This bug lead to problems in lm_optimizer.py
=> Bug fix - test_csvs argument was ignored

native_client/javascript/index.js
The Node.js binding for `stream.intermediateDecodeWithMetadata()` was calling `binding.IntermediateDecode()` instead of `binding.IntermediateDecodeWithMetadata()` which would always cause the error:
```
Illegal number of arguments for _wrap_IntermediateDecode
```
Verified that this works as expected after the fix.
=> Fix JS IntermediateDecodeWithMetadata binding

native_client/ctcdecode/ctc_beam_search_decoder.cpp
This should eliminate confusion where the adjusted order does not match the sorted order as well as avoid behavior discrepancies between runs with and without a scorer.
=> Return raw scores in confidence value (Fixes #3004)

training/deepspeech_training/util/feeding.py
pcm_to_np takes segment buffer as its first argument and audio format as a second one. The wrong order cause "bytes object has no attribute 'channels'' ArgumentError.
=> Fix arguments order in pcm_to_np call

doc/USING.rst
Hello there.
I have added DeepSpeech bindings for [nim-lang](https://nim-lang.org) and wanted to add it into the 3rd Party Bindings list.
I am using `git tags` starting with DeepSpeech's version `0.7.x`  and  hoping to use tag system for handling changes/breakage in upcoming API.
=> Added third-party bindings for NIM-lang.

Dockerfile.train.tmpl
The already installed pip versions of opuslib and numba also work.
=> Add dependencies for new audio augmentation flags. Fixes #3082.

Dockerfile.train.tmpl, doc/TRAINING.rst
No longer needed since we started publishing ds_ctcdecode on PyPI.
=> Remove --force-reinstall from training code install

native_client/ctcdecode/scorer.cpp, native_client/ctcdecode/scorer.h
This method was made unused by https://github.com/mozilla/DeepSpeech/pull/3021
after reports such as https://github.com/mozilla/DeepSpeech/issues/3004
of confusion interpreting the confidence values.
=> Remove unused Scorer method

doc/USING.rst
I don't think this was adding any useful information and because we have different training and inference versions right now it adds to the confusion a bit.
=> Remove mention of TensorFlow docs for CUDA requirements

native_client/ctcdecode/__init__.py, native_client/ctcdecode/ctc_beam_search_decoder.cpp, native_client/ctcdecode/ctc_beam_search_decoder.h
Allows the specification of number of returned candidates with `ds-ctcdecoder` package.
=> Add num_results param to ctc_beam_search_decoder

native_client/ctcdecode/ctc_beam_search_decoder.cpp
I have encountered a case where my alphabet file was wrong (one extra letter in it), and it resulted in issues difficult to debug. So, I suggest to add a check there.
=> In ctc_beam_search_decoder(), added a sanity check between input class_dim and alphabet

Dockerfile.train.tmpl
This is a simple fix for being able to build once again any release DS following problems that have arisen after setuptool 50.0.0 release. 
https://github.com/mozilla/DeepSpeech/issues/3295#issuecomment-685476173
Cheers!
=> Fix for setuptools._distutils issue (#3295)

doc/TRAINING.rst
As discussed yesterday, this is the fix for this [PR](https://github.com/mozilla/DeepSpeech/pull/3314). 
And looks like Atom found a trailing whitespace.
=> Simplified git clone msg to prevent error reportings

bin/import_swb.py
Was using this script and noticed the missing `os` import.
=> Added `os` import in front of `makedirs`

native_client/BUILD, native_client/ctcdecode/build_archive.py, native_client/ctcdecode/ctc_beam_search_decoder.cpp, native_client/ctcdecode/ctc_beam_search_decoder.h, native_client/ctcdecode/path_trie.cpp, native_client/ctcdecode/path_trie.h, native_client/ctcdecode/scorer.cpp, native_client/ctcdecode/third_party/object_pool/README.mozilla, native_client/ctcdecode/third_party/object_pool/object_pool.h, native_client/ctcdecode/third_party/object_pool/unique_ptr.h
This follows the issue #3180 .
I suggest a new way of handling timesteps produced by the CTC decoder. There is no strange heuristic, and I think the logic is clear : when fusing two different paths leading to the same prefix, not only fuse the probabilities (the probabilities are added), but also fuse the timestep sequences (for the last letter in the sequence, choose the timestep from the most probable path).
The place where two different paths leading to the same prefix are fused are the places where `log_sum_exp` is called, because this function fuses the probabilities. So, timesteps would now be fused at the same places.
The other change is that each `PathTrie` node would now store the full sequence of timesteps. This is because one prefix can be an ancestor of another and their …
=> The CTC decoder timesteps now corresponds to the timesteps of the most probable CTC path, instead of the earliest timesteps of all possible paths.

native_client/javascript/client.ts, native_client/javascript/index.ts, taskcluster/tc-node-tests.sh, taskcluster/tc-node_tflite-tests.sh
This PR enables hot-word boosting for Javascript Binaries. 
For the issue #3336
=> enable hot-words boosting for Javascript

native_client/python/__init__.py
As the parameter for boost was actually written as "word" in the doc string, it was replacing the previous type for word with the type intended for boost and not showing any type for boost, thus messing up what displayed on https://deepspeech.readthedocs.io/en/master/Python-API.html
=> Tiny fix to addHotWord doc string parameters

bin/import_cv2.py
When running a training session on the CV2 dataset, it is possible to get the following error:
```
ValueError: Mono-channel audio required
```
This makes the [pysox Transformer](https://pysox.readthedocs.io/en/latest/api.html#sox.transform.Transformer.convert) also convert the channels.
```
bin/import_cv2.py --filter_alphabet data/alphabet.txt data/cv2/cv-corpus-5.1-2020-06-22/en/
```
=> Convert channels for CV2 dataset

training/deepspeech_training/train.py, training/deepspeech_training/util/audio.py, training/deepspeech_training/util/augmentations.py, training/deepspeech_training/util/check_characters.py, training/deepspeech_training/util/config.py, training/deepspeech_training/util/downloader.py, training/deepspeech_training/util/evaluate_tools.py, training/deepspeech_training/util/helpers.py, training/deepspeech_training/util/io.py, training/deepspeech_training/util/sample_collections.py, training/deepspeech_training/util/taskcluster.py
Offering this up as a PR in case it's useful to more people than just me.
This refactors the training code to use a set of I/O helpers that allow for remote file access, right now using TensorFlow's GFIle API, allowing us to pass in files like `gs://my-bucket/my/path` or `hdfs://...`. This can be extended to AWS `s3://...` paths relatively easily.
Most of the refactoring is fairly straightforward. Things get a little bit more complicated with `AudioFile`, since you pass a local file to sox for the conversion. I've just wrapped that into a copy in a tmpfile, since I assume the conversion overhead prevails here and there was a reason for doing things this way.
I did this because I wanted to bring in datasets that I have on distributed storage and train on GCP AI platform, but I'd also be …
=> Remote I/O Training Setup

.dockerignore, bin/compare_samples.py, training/deepspeech_training/train.py, training/deepspeech_training/util/audio.py, training/deepspeech_training/util/augmentations.py, training/deepspeech_training/util/taskcluster.py
This fixes the I/O issues with taskcluster.py introduced in #3420. Also adds a small `.dockerignore` for faster local docker img builds.
=> Fix I/O issues introduced in #3420

native_client/generate_scorer_package.cpp
The error message for an unreadable lm binary file is misleading. We just had a user [who wanted to build a scorer](https://discourse.mozilla.org/t/error-while-generating-own-scorer/70945/4) with `generate_scorer` and got the message "Could not read the scorer file." But he is missing the right lm.binary file. It would therefore be better to state that.
@reuben I changed the output to change the msg in case it the the 
`DS_ERR_SCORER_UNREADABLE` message. And I haven't been coding C++ for a long time, hope that's fine with you.
=> Conditional msg for missing lm.binary added

native_client/javascript/index.ts
In TypeScript, I would like to be able to do this:
```typescript
let inferenceStream: Deepspeech.Stream | null = null
```
To then initialize it later. However, the Stream class is not exported, and as a result neither is its type definition, meaning I cannot import it. This PR just adds the export keyword to solve this.
=> Export the Stream class so type information can be imported

native_client/definitions.mk
Solves #3379
- Makes building ctcdecode on PowerPC `ppc64le` and other non x86/arm systems with linux possible
- set `PYTHON_PLATFORM_NAME` and `SWIG_DIST_URL` in environment
- For `ppc64le` set `PYTHON_PLATFORM_NAME="--plat-name linux_ppc64le"`.  This should be mentioned somehow in docu
- It should also be mentioned to use https://github.com/lissyx/swig/tree/taskcluster instead of plain swig
=> build ctcdecode on ppc64le

doc/BUILDING.rst
As mentioned in  #3505 and #3379 I documented how to build ctc decoder on ppc64le
=> Docu building ctc decoder on unsupported architecture

native_client/swift/deepspeech_ios/DeepSpeech.swift
Currently, attempting to access member fields DeepSpeechTokenMetadata objects output from intermediateDecodeWithMetadata causes a crash. Changing these lines makes the object work as (I assume) intended.
=> Swift iOS Bindings: Expose DeepSpeechTokenMetadata fields

native_client/swift/deepspeech_ios.xcodeproj/project.pbxproj, native_client/swift/deepspeech_ios_test.xcodeproj/xcshareddata/xcschemes/deepspeech_ios_test.xcscheme
Fixes `module compiled with Swift 5.1.3 cannot be imported by the Swift 5.3.2`. 
Tested by following [these](https://github.com/mozilla/DeepSpeech/pull/3436) instructions.
=> Fix incompatible Swift module error

doc/HotWordBoosting-Examples.rst, doc/index.rst, native_client/deepspeech.h, native_client/dotnet/DeepSpeechClient/DeepSpeech.cs, native_client/java/libdeepspeech/src/main/java/org/deepspeech/libdeepspeech/DeepSpeechModel.java, native_client/javascript/index.ts, native_client/python/__init__.py
Based on my post on Discourse Mozilla forum: 
https://discourse.mozilla.org/t/practical-tests-of-hot-word-feature-and-default-models-accuracy/73855
I've added an example & guideline docs for hot-word boosting since those are missing. Also, not sure if the category for this document is correct.
=> Added hot-word boosting doc

bin/import_fisher.py, bin/import_swb.py
Fixes #3511: https://github.com/mozilla/DeepSpeech/issues/3511
Changes the `_split_sets` helper function in `bin/import_swb.py` and `bin/import_fisher.py` to split the training, validation, and test sets based on a sample size using a 99% confidence and 1% margin of error. The `get_sample_size` function was copied from `bin/import_swc.py`.
=> Fix #3511: split-sets on sample size

doc/TRAINING.rst, setup.py, training/deepspeech_training/train.py, training/deepspeech_training/util/config.py, training/deepspeech_training/util/feeding.py, training/deepspeech_training/util/flags.py
As already mentioned in Discourse we implemented distributed training using [Horovod](https://github.com/horovod/horovod).
We tried to keep the changes as minimal as possible. It is still possible to run your undistributed code version. However we also noticed a slightly improvement by using Horovod on one machine.
We copied your `train`-function to `train_with_horovod` but I can also provide an merge by using some `if FLAGS.horovod`. This would reduce code duplication. It is just to improve readability at the moment.
While our code has a good scaling on local stored datasets, we experienced a lack of performance on datasets stored on you globally distributed filesystem (BeeGFS). This could be caused by `tf.data.Dataset.shard`. We will investigate on this.
=> Implement distributed training using horovod

training/deepspeech_training/train.py, training/deepspeech_training/util/audio.py
This PR cleans up #3559 per @lissyx's request.
Now adds the following two bits:
1. https://github.com/mozilla/DeepSpeech/commit/66f4ed4c65a54ed2e84b263abbfb78ae696b5d40 exposes a couple of the hidden per-CTC-output layers for downstream applications that wish to use deepspeech internal representations
2. https://github.com/mozilla/DeepSpeech/commit/877fef9f2eb49f51a7fa02cd22af312f11c1e957 and https://github.com/mozilla/DeepSpeech/commit/444654036763bdf2bb50826a38426a6f62352963 add multi-channel-to-mono conversion along the way to the `pcm_to_np()` function. In a previous PR (#3512), I had proposed using `AudioFile` as a wrapper for all samples to handle sample rate and channel conversion. @reuben pointed out that sample rate was already handled elsewhere and that TensorFlow's functions …
=> Small Training Tweaks
