- DeepSpeech.ipynb
Added checkpointing, more complicated model persistence should wait until TensorFlow Serving is integrated as it imposes other specifications on serialization.
> Added checkpointing

- util/log.py
> Ensure merge_logs() sorts directory

- DeepSpeech.ipynb
> Using env variables to control execution parameters

- bin/run-ldc93s1.sh
- util/importers/ldc93s1.py
> LDC93S1 Simple sample importer

- DeepSpeech.ipynb
> Introduce ds_checkpoint_dir to change checkpointing directory

- bin/run-wer-automation.sh
> Fix TED LIUM automation path

- util/importers/librivox.py
- util/importers/ted_lium.py
@reuben could you review this change
> Fixes #101

- index.htm
Also corrected wrong WER usage for parameter based charts.
@lissyx : Please review.
> Fix #113; Showing real WER values

- index.htm
> Fix #115; Time based charts now with timeline on the bottom

- README.website.md
- util/automation.py
> Switch dependency from xdg to pyxdg

- util/automation.py
> Verify date of merges when pulling list of changes

- README.md
> Adding sox README.md

- util/importers/ted.py
@andrenatal Is this OK for testing purposes?
> Fix #144; Ability to limit amount of samples in TEDLIUM

- bin/run-wer-automation.sh
Set importer to 'ted' instead of 'ted_lium', fixes #149
Set batch_size to 32, fixes #150
> Change automation parameters

- bin/run-wer-automation.sh
> Limit training epochs to 6

- bin/run-wer-automation.sh
- util/automation.py
This breaks restore feature. We should let code overwrite existing
checkpoints.
Fixes #166
> Do not remove existing checkpoint dirs

- index.htm
> Fix #134; better axis description and value plotting in WER report page

- DeepSpeech.ipynb
@kdavis-mozilla Could you take a look?
> Fix #132 #126 - Inlined WER report inference into train loop

- DeepSpeech.ipynb
Moved graph creation to before the lines
tf.train.start_queue_runners(sess=session)
data_sets.start_queue_threads(session)
so as to not have the queue threads operate on a graph that is being
modified.
> Fixed #193

- README.website.md
- bin/run-ldc93s1.sh
- bin/run-librivox.sh
- bin/run-ted.sh
- bin/run-wer-automation.sh
> Forcing python to not buffer output

- README.website.md
- bin/gpu_usage_chart
- bin/gpu_usage_plot
- util/automation.py
> Tracking GPU Usage

- DeepSpeech.ipynb
> Fix #219; Fixed wrong duration formatting

- DeepSpeech.ipynb
@kdavis-mozilla This is the slightly optimized WER calculation using ```distance=0``` as ```WER=0``` exclusion criteria. Please take a look.
> Fix #188; Using distances to filter WERs

- DeepSpeech.ipynb
@kdavis-mozilla Just removed the assignments. Please take a look.
> Fixed #231

- util/automation.py
> Restore checkpoint automatically based on some rules

- index.htm
> Validation and training WER labels are mis-reported

- README.md
I also fixed the part that said we depend on IronPython (what! :P) and made the dependency on Paramiko for the website stuff be optional.
> Update README.me to mention run-ldc93s1.sh and be more explicit about GPU requirements

- bin/run-fisher.sh
- util/importers/fisher.py
- util/text.py
I left some logging in since this is a long running process and it's useful to know how things are going. This code also does not delete any of the original files since disk is cheap and this makes it faster to fix the importer if something is wrong.
I haven't done a full run with the train/dev/test splitting code yet, I'll do that when the server is not being used.
> Implement Fisher corpus importer

- README.website.md
- bin/run-wer-automation.sh
- util/automation.py
Touching both TMP= and forcing CKPT_BASE_DIR to be on /data
Fixes #374
> Move big data write to /data

- DeepSpeech.py
- util/importers/LDC97S62.py
- util/importers/fisher.py
- util/importers/ldc93s1.py
- util/importers/librivox.py
- util/importers/ted.py
I completed one full TED epoch on the server with this code without problems.
> Don't create DataSet objects for data sets we will not use

- DeepSpeech.py
Some minor fixes I made while working on #340.
> Minor fixes

- DeepSpeech.py
Commit 6e4f54b1f13dd01589a74ede5323efe0a198ca4a fixed the underlying bug that used to require this extra test, so we just need to remove it.
> Allow checkpointing and validation at end of epoch 0 (fixes #392)

- README.md
Added doc indicating git lfs is required
> Fixed #398

- native_client/Makefile
- native_client/multistrap.conf
> Support RPi toolchain cross-compilation of native client

- native_client/Makefile
> Fix libaries ordering for linker

- native_client/client.cc
> Measure execution time in native_client

- native_client/client.cc
> Fix possible NULL deref on result->string

- native_client/Makefile
@Cwiiis if you can think of a more elegant way to do this, I'm all ears.
> Fixed #460

- README.md
> update requirement.txt file path

- bin/run-ted.sh
> Update run-ted.sh with hyperparameters from run-wer-automation.sh

- DeepSpeech.py
- native_client/deepspeech.cc
> Export graph should take sequence lengths as input

- native_client/deepspeech.cc
> Pass correct input_lengths value as a Tensor to Session::Run()

- DeepSpeech.py
- bin/run-fisher.sh
- bin/run-ldc93s1.sh
- bin/run-librivox.sh
- bin/run-swb.sh
- bin/run-ted.sh
@reuben 
If I understood this was the right solution. From the original post below I have added the try catch around the "with tf.train.MonitoredTrainingSession" call in train.  The message I am providing the user may need to be adjusted to make it better and I am open to suggestions/corrections. 
The original post below describes my reasoning for this proposed changed. I hope I did this correctly.
The documentation in the README.md can be updated so that search engines can point here for this issue.
pro's:
-  No change to code. 
-  People will discover that default checkpoints can this error by mixing models with different shapes.
con's:
- Other people may associate this error with Deep Speech itself. (either way people find what may be triggering this in TF)
Change the empty flag …
> fix for issue 511

- bin/run-fisher.sh
- bin/run-ldc93s1.sh
- bin/run-librivox.sh
- bin/run-swb.sh
- bin/run-ted.sh
> Use pyxdg in the bin/run-* scripts to find out where to put checkpoints

- util/stm.py
The importer cleanup PR left this code broken.
> Open STM files as UTF-8

- DeepSpeech.py
- bin/run-ldc93s1.sh
removed the new checkpoint directory that was created in the prev PR.
> updated minor fixes

- DeepSpeech.py
- bin/run-ted.sh
- bin/run-wer-automation.sh
Fixed by putting the `grad = tf.concat(grads, 0)` on host not device
> Fixed issue #608

- DeepSpeech.py
@tilmankamp , @kdavis-mozilla : Request you to have a look at this?
I have added few additional FLAG parameters such as (mean_loss_thresh and std_loss_thresh) to take care of the slight fluctuations in the past n_steps (configurable too).
By default, the early_stop flag has been enabled and validation_step is disabled so it will just show a warning message as:
_W Validation flag needs to be enabled for Early Stopping to work
I STARTING Optimization
I Training of Epoch 0 - loss: 363.021423_
**Test Cases:**
DataSet: LDC93S1
**Variations:** Changed the epochs to 50 and 150 to see if the Early Stopping is being triggered.
**With 50 epochs:**
Early stopping isn't triggered as expected from the logs of losses over Validation dataset
**With 150 epochs:**
Early stopping triggered at epoch 62. …
> Fix #538; Early stopping

- DeepSpeech.py
@tilmankamp : Updated the documentation. Please have a look
> Fix #658; Update the documentation for Early Stopping parameter

- README.md
Please review this risky change thoroughly.
> Update README.md to not suggest TF serving is used

- native_client/setup.py
> Change library link ordering for python binding

- DeepSpeech.py
@tilmankamp , @kdavis-mozilla , @reuben : Fix for early stopping trigger after 1st epoch. Turns out validation losses were collected for all the jobs from the single epoch as different epochs on when running on GPUs. Now they are accumulated epoch wise and then considered for decision based on previous 'earlystop_nsteps' epochs.
> Fix #667; early stop and export warning

- DeepSpeech.py
@tilmankamp , @kdavis-mozilla : Can you have a look at this?
> Fix #695; Checkpoint is not resuming from left off point

- bin/import_voxforge.py
- requirements.txt
Add an importer for [voxforge](http://www.voxforge.org/home) dataset(~118 hour), use 1/100 for test, 1/100 for dev.
> Add importer for voxforge dataset

- bin/import_ldc93s1.py
delete unused and non-exist module data_set_helper
> delete non-exist import module

- native_client/setup.py
> Add scipy and numpy deps to deepspeech python bindings

- native_client/client.py
> Make native_client/client.py compatible with Py3

- native_client/client.cc
- native_client/client.js
> Fix node client.js model.stt() buffer size call

- .taskcluster.yml
- .tc.cpp-ds-tests.yml
- .tc.node-tests.yml
- .tc.python-tests.yml
- .tc.training.yml
- bin/run-tc-ldc93s1.sh
- tc-build.sh
- tc-cpp-ds-tests.sh
- tc-node-tests.sh
- tc-python-tests.sh
- tc-schedule-tasks.sh
- tc-tests-utils.sh
- tc-train-tests.sh
Fixes #751
Trains a model and schedule C++, Python and NodeJS tests.
> TaskCluster-based training and testing of DeepSpeech

- bin/import_swb.py
Minor changes to make SWB import work again
> Fixed #773

- README.md
> Provide TaskCluster badge in README

- DeepSpeech.py
- util/feeding.py
- util/text.py
Sorry, I didn't test the code on Python 2 :(
> Make sure custom alphabet code works properly on Python 2

- bin/import_voxforge.py
- requirements.txt
Hey @gardenia22 can you review these changes? I've tested on Python 2 and 3.
> Upgrade VoxForge importer to BeautifulSoup 4 and fix Python 2/3 compat

- native_client/client.cc
> Check benchmark argument against proper argv

- taskcluster/darwin-opt-base.tyml
- taskcluster/linux-opt-base.tyml
> Set proper artifacts expiration dates

- taskcluster/darwin-opt-base.tyml
> Change all path on OSX after extracting home.tar.xz

- native_client/c_speech_features/c_speech_features.c
- native_client/deepspeech_utils.cc
> Proper call of calloc()

- native_client/Makefile
- native_client/definitions.mk
- native_client/javascript/Makefile
- native_client/javascript/binding.gyp
- native_client/multistrap.conf
- native_client/setup.py
> Cleanup makefile

- README.md
Fix header in readme.md- #installation
>  Fix header in readme.md- #installation

- native_client/setup.py
- requirements.txt
> Stick to scipy 0.19.1

- native_client/Makefile
- native_client/README.md
- native_client/definitions.mk
- native_client/javascript/Makefile
- native_client/setup.cfg
And also improve some other details.
> Update docs to highlight prebuilt binaries

- bin/import_voxforge.py
> parallelized import_voxforge.py

- native_client/setup.py
- tc-python-tests.sh
> Remove scipy dependency from Python bindings

- native_client/Makefile
- native_client/definitions.mk
- native_client/javascript/Makefile
- native_client/multistrap.conf
- native_client/setup.py
- taskcluster/.shared.yml
- taskcluster/linux-amd64-cpu-opt.yml
- taskcluster/linux-rpi3-cpu-opt.yml
- taskcluster/rpi3-build.sh
- tc-tests-utils.sh
> Prebuilt ARM Python & NodeJS bindings

- taskcluster/linux-amd64-ctc-opt.yml
> Add missing routes entry for libctc

- taskcluster/.build.yml
- taskcluster/linux-amd64-cpu-opt.yml
- taskcluster/linux-opt-base.tyml
- taskcluster/linux-rpi3-cpu-opt.yml
- taskcluster/test-benchmark-linux-amd64-opt.yml
- taskcluster/test-linux-opt-base.tyml
- taskcluster/test-nodejs_4x-linux-amd64-opt.yml
- taskcluster/test-nodejs_5x-linux-amd64-opt.yml
- taskcluster/test-nodejs_6x-linux-amd64-opt.yml
- taskcluster/test-python_27-linux-amd64-opt.yml
- taskcluster/test-python_34-linux-amd64-opt.yml
- taskcluster/test-python_35-linux-amd64-opt.yml
- taskcluster/test-python_36-linux-amd64-opt.yml
- taskcluster/test-training-linux-amd64-opt.yml
Array to sr() was undocumented and is not supported in JS.
Fixes #925
> Proper definition of .build.yml

- native_client/Makefile
- native_client/definitions.mk
> Use sox include/link flags only on deepspeech binary

- taskcluster/linux-amd64-cpu-aot_test-opt.yml
> Set routes to empty for AOT Test build

- taskcluster/linux-amd64-cpu-aot_test-opt.yml
Reverts mozilla/DeepSpeech#941
> Revert "Set routes to empty for AOT Test build"

- taskcluster/.build.yml
- taskcluster/linux-amd64-cpu-aot_test-opt.yml
- taskcluster/linux-amd64-ctc-opt.yml
- taskcluster/linux-opt-base.tyml
- tc-schedule.sh
> Properly limit scheduling of some tasks to PR or merge

- .taskcluster.yml
- taskcluster/.shared.yml
- taskcluster/darwin-amd64-cpu-opt.yml
- taskcluster/linux-amd64-cpu-opt.yml
- taskcluster/test-linux-opt-base.tyml
> TaskCluster IRC notifications

- taskcluster/test-cpp-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-linux-opt-base.tyml
- taskcluster/test-nodejs_4x-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-nodejs_5x-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-nodejs_6x-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-python_27-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-python_34-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-python_35-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-python_36-linux-amd64-prod_pbmodel-opt.yml
- tc-cpp-ds-tests-prod.sh
- tc-node-tests-prod.sh
- tc-node-tests.sh
- tc-python-tests-prod.sh
- tc-tests-utils.sh
> Run test coverage against prod-similar model

- README.md
- native_client/README.md
> Add virtualenv documentation for Python

- native_client/Makefile
- native_client/setup.py
> Ensure _model.so and _utils.so are inside DeepSpeech package

- README.md
- native_client/README.md
Reverts mozilla/DeepSpeech#1008
> Revert "Update docs to point to npm packages"

- native_client/javascript/client.js
- native_client/python/client.py
> Add runtime execution time feedback

- README.md
- native_client/README.md
> Document deps

- .taskcluster.yml
> Switch to JSON-e fixes version

- README.md
This is current until #1022 is resolved.
> Adding note about audio file format requirements.

- README.md
> Update README.md for r1.4-based

- taskcluster/darwin-opt-base.tyml
> Set minimum OSX version to 10.10

- native_client/BUILD
- native_client/Makefile
> Improve OSX linkage

- tc-tests-utils.sh
> Remove OSX-specific wget/gunzip hack

- taskcluster/.build.yml
- taskcluster/.shared.yml
- taskcluster/test-cpp-darwin-amd64-opt.yml
- taskcluster/test-darwin-opt-base.tyml
- taskcluster/test-linux-opt-base.tyml
- taskcluster/test-nodejs_4x-darwin-amd64-opt.yml
- taskcluster/test-nodejs_5x-darwin-amd64-opt.yml
- taskcluster/test-nodejs_6x-darwin-amd64-opt.yml
- taskcluster/test-nodejs_7x-darwin-amd64-opt.yml
- taskcluster/test-nodejs_8x-darwin-amd64-opt.yml
- taskcluster/test-nodejs_9x-darwin-amd64-opt.yml
- taskcluster/test-python_27-darwin-amd64-opt.yml
- taskcluster/test-python_34-darwin-amd64-opt.yml
- taskcluster/test-python_35-darwin-amd64-opt.yml
- taskcluster/test-python_36-darwin-amd64-opt.yml
- tc-brew-tests.sh
- tc-cpp-ds-tests-prod.sh
- tc-cpp-ds-tests.sh
- tc-node-tests-prod.sh
- tc-node-tests.sh
- tc-python-tests-prod.sh
- tc-python-tests.sh
- tc-tests-utils.sh
> Add OSX testing

- README.md
Hey guys,
I've implemented some Golang bindings for your awesome library. Could be useful to let developers know about it so that they can start working with your library quicker if their preferred language is Go.
Cheers
> [Docs] Add Golang third party bindings

- README.md
<sub><b>This PR does basically aim at:</b></sub>:
- <sub>*attempting at fixing minor issues with language*</sub>
- <sub>*adding thumbnail images*</sub>
---
<sub>**main reason behind such:**</sub>
- <sub>*improving overall document accessebility*</sub>
---
<sub>***LET'S MAKE THE WEB BETTER BIT BY BIT***</sub>
<sub>***EVER TRIED. EVER FAILED. NO MATTER. TRY AGAIN. FAIL AGAIN. FAIL BETTER***</sub>
---
> [Docs] - README.md - minor attempt at improving language, adding thumbnail images

- README.md
Referring to @lissyx 's request in issue #979
> README: Point to 3rd party arch linux PKGBUILDs

- native_client/Makefile
- native_client/definitions.mk
- native_client/setup.py
- taskcluster/.build.yml
- taskcluster/test-linux-opt-base.tyml
- taskcluster/test-training+deepspeech-linux-amd64-py27-opt.yml
- taskcluster/test-training+deepspeech-linux-amd64-py36-opt.yml
- taskcluster/test-training_upstream+deepspeech-linux-amd64-py27-opt.yml
- taskcluster/test-training_upstream+deepspeech-linux-amd64-py36-opt.yml
- tc-train-tests.sh
> Avoid over-linking deepspeech.utils Python wrapper

- native_client/python/client.py
> adding assert for input wav file frequency check in client.py

- DeepSpeech.py
https://github.com/mozilla/DeepSpeech/issues/999
> Fix absl.flags._exceptions #999

- taskcluster/darwin-amd64-cpu-aot_prod-opt.yml
- taskcluster/darwin-amd64-cpu-opt.yml
- taskcluster/linux-amd64-cpu-aot_prod-opt.yml
- taskcluster/linux-amd64-cpu-aot_test-opt.yml
- taskcluster/linux-amd64-cpu-opt.yml
- taskcluster/linux-amd64-ctc-opt.yml
- taskcluster/linux-amd64-gpu-opt.yml
- taskcluster/linux-rpi3-cpu-aot_prod-opt.yml
- taskcluster/linux-rpi3-cpu-opt.yml
- taskcluster/node-package.yml
- taskcluster/test-training+deepspeech-linux-amd64-py27-opt.yml
- taskcluster/test-training+deepspeech-linux-amd64-py36-opt.yml
- taskcluster/test-training-linux-amd64-py27-opt.yml
- taskcluster/test-training-linux-amd64-py34-opt.yml
- taskcluster/test-training-linux-amd64-py35-opt.yml
- taskcluster/test-training-linux-amd64-py36-opt.yml
sed \
-ri 's/pip\.master\./pip.master.1390dc180e25b5821be80b407ddc5fad73d4ef6a./g' \
taskcluster/*.yml
Fixes #1177
> Switch URLs to commit-based

- taskcluster/.shared.yml
> Switch to swig 3.0.10-1.2

- README.md
> Update docs and remove specific TensorFlow instructions

- util/feeding.py
This should prevent the float not iterable problems.
> Make sure transcript field isn't coerced to float

- README.md
- bin/benchmark_nc.py
- native_client/client.cc
- native_client/javascript/client.js
- native_client/python/client.py
- tc-tests-utils.sh
This PR resolves #1032 
This makes audio clip the last argument as requested. 
In client.cc I also changed the index at various location as in c++ CL arguments come as an list not as a dictionary unlike in node.js and python.
> reorder arguments in client.cc, client.py and client.js. 

- native_client/client.cc
- tc-cpp-ds-tests.sh
- tc-tests-utils.sh
> Multiple audio native_client benchmark

- native_client/BUILD
- native_client/deepspeech.cc
- taskcluster/.build.yml
- taskcluster/darwin-amd64-cpu-aot_prod-opt.yml
- taskcluster/darwin-amd64-cpu-opt.yml
- taskcluster/linux-amd64-cpu-aot_prod-opt.yml
- taskcluster/linux-amd64-cpu-aot_test-opt.yml
- taskcluster/linux-amd64-cpu-opt.yml
- taskcluster/linux-amd64-ctc-opt.yml
- taskcluster/linux-amd64-gpu-opt.yml
- taskcluster/linux-rpi3-cpu-aot_prod-opt.yml
- taskcluster/linux-rpi3-cpu-opt.yml
- taskcluster/node-package.yml
- taskcluster/test-darwin-opt-base.tyml
- taskcluster/test-linux-opt-base.tyml
- taskcluster/test-training_upstream-linux-amd64-py27-opt.yml
- tc-cpp-ds-tests-prod.sh
- tc-node-tests-prod.sh
- tc-python-tests-prod.sh
- tc-tests-utils.sh
- tc-train-tests.sh
> Support MemmappedFileSystem

- README.md
- native_client/README.md
- taskcluster/test-linux-opt-base.tyml
> Update doc for mmap-able model

- native_client/README.md
> Fix doc with no --config=monolithic for libctc_decoder_with_kenlm.so

- taskcluster/test-darwin-opt-base.tyml
- taskcluster/test-linux-opt-base.tyml
> Increase pip default timeout

- native_client/BUILD
- native_client/client.cc
- native_client/deepspeech.cc
- native_client/deepspeech.h
- native_client/ds_git_version.sh
- taskcluster/darwin-amd64-cpu-aot_prod-opt.yml
- taskcluster/darwin-amd64-cpu-opt.yml
- taskcluster/linux-amd64-cpu-aot_prod-opt.yml
- taskcluster/linux-amd64-cpu-aot_test-opt.yml
- taskcluster/linux-amd64-cpu-opt.yml
- taskcluster/linux-amd64-ctc-opt.yml
- taskcluster/linux-amd64-gpu-opt.yml
- taskcluster/linux-rpi3-cpu-aot_prod-opt.yml
- taskcluster/linux-rpi3-cpu-opt.yml
- taskcluster/node-package.yml
- taskcluster/test-darwin-opt-base.tyml
- taskcluster/test-linux-opt-base.tyml
- taskcluster/test-training_upstream-linux-amd64-py27mu-opt.yml
- tc-cpp-ds-tests-prod.sh
- tc-cpp-ds-tests.sh
- tc-tests-utils.sh
> Expose versions numbers on stderr

- .taskcluster.yml
- RELEASE.md
- taskcluster/github-events.cyml
> Add missing branch filtering for v0.2.0-alpha.0

- .taskcluster.yml
- RELEASE.md
- taskcluster/github-events.cyml
- taskcluster/scriptworker-task.yml
> Use new 'tag' event

- README.md
> Improve doc wrt Common Voice 'other'

- README.md
> Fix leftover example CLI call

- tc-tests-utils.sh
> Fix OpenSSL package version

- taskcluster/.shared.yml
- taskcluster/test-python_37-darwin-amd64-opt.yml
- taskcluster/test-python_37-linux-amd64-aot_test-opt.yml
- taskcluster/test-python_37-linux-amd64-opt.yml
- taskcluster/test-python_37-linux-amd64-prod_pbmodel-opt.yml
- tc-tests-utils.sh
> Switch to Python 3.7.0 stable

- README.md
- native_client/README.md
- util/taskcluster.py
> Augment tc download with branch

- native_client/definitions.mk
- native_client/setup.py
- tc-tests-utils.sh
> WIP: Require NumPy API v7

- README.md
- bin/benchmark_nc.py
- native_client/Makefile
- native_client/README.md
- native_client/args.h
- native_client/client.cc
- native_client/javascript/client.js
- native_client/python/client.py
- tc-tests-utils.sh
> Non positionnal arguments. Everywhere.

- DeepSpeech.py
I did this on top of 7c43ebd / #1391 because I'm rebasing the streaming inference branch on top of both these commits, so you'll probably want to review just commit 806ef16 here, or do the reviews for both PRs in a single pass on this PR.
Sorry for the inconvenience, I wish I knew git well enough to make this work from separate branches. Maybe cherry-picking is the answer...
> Disable dropout in evaluation steps (Fixes #1262)

- DeepSpeech.py
(had problems rebasing/merging, decided just to make new PR) 
Previous PR: #1482
> added progressbar

- .compute
- .gitignore
- .install
- Based on 0.1.1 hyperparameters
- Successfully started a test training 
- This will/should not get merged before test training concludes
> Default training setup for new cluster

- taskcluster/test-armbian-opt-base.tyml
- taskcluster/test-raspbian-opt-base.tyml
> Ensure xxd is installed

- DeepSpeech.py
- evaluate.py
- native_client/deepspeech.cc
- requirements.txt
- tc-tests-utils.sh
- util/audio.py
- util/feeding.py
- util/preprocess.py
This doubles as road-paving for an easier tf.data.Dataset implementation of the feeding code.
> Feature caching

- taskcluster/scriptworker-task.yml
- taskcluster/simple-task.tyml
> Add CPP artifact deps

- .taskcluster.yml
- taskcluster/github-events.cyml
> Add tag event

- taskcluster/.build.yml
- taskcluster/darwin-amd64-cpu-aot_prod-opt.yml
- taskcluster/darwin-amd64-cpu-opt.yml
- taskcluster/darwin-opt-base.tyml
- taskcluster/linux-amd64-cpu-aot_prod-opt.yml
- taskcluster/linux-amd64-cpu-opt.yml
- taskcluster/linux-amd64-gpu-opt.yml
- taskcluster/linux-opt-base.tyml
- taskcluster/linux-rpi3-cpu-aot_prod-opt.yml
- taskcluster/linux-rpi3-cpu-opt.yml
- taskcluster/scriptworker-task.yml
- taskcluster/simple-task.tyml
- taskcluster/test-darwin-opt-base.tyml
- taskcluster/test-linux-opt-base.tyml
- tc-schedule.sh
> Improve tag handling

- taskcluster/scriptworker-task.yml
> Remove ARM64 dep on 0.1.1

- Dockerfile
- taskcluster/docker-build-base.tyml
- taskcluster/docker-image-build.yml
> Adding TaskCluster testing of docker build

- native_client/javascript/client.js
- native_client/python/client.py
> Enforce same sox options as libsox for C++ client

- native_client/beam_search.h
- tc-tests-utils.sh
> Fix missing field in struct copy

- bin/import_ts.py
importer for https://github.com/mozilla/DeepSpeech/issues/1576
Produces 3 `<target_dir>/ts_<ARCHIVE_NAME>_(dev|train|test).csv`  files
containing respectively
```
$ wc -l <target_dir>/ts_2018-09-28_fr*          
5603 <target_dir>/ts_2018-09-28_fr_FR_dev.csv
5603 <target_dir>/ts_2018-09-28_fr_FR_test.csv
44811 <target_dir>/ts_2018-09-28_fr_FR_train.csv
56017 total
```
and look like:
```
$ head -n 5 <target_dir>/training_speech_2018-09-28_fr_FR_*  
==> <target_dir>/ts_2018-09-28_fr_FR_dev.csv <==
wav_filename,wav_filesize,transcript
<target_dir>/ts_2018-09-28_fr_FR/LeComteDeMonteCristoT1Chap1_0004.wav,219564,aussitôt comme d'habitude encore la plate forme du fort saint jean s'était couverte de curieux
<target_dir>/ts_2018-09-28_fr_FR/LeComteDeMonteCristoT1Chap1_0019.wav,161868,qu'est il …
```
> setup training_speech importer (see #1576)

- bin/import_cv.py
I have no idea how this ever worked.
> Fix import_cv.py

- DeepSpeech.py
- evaluate.py
- native_client/ctcdecode/COPYING
- native_client/ctcdecode/LICENSE.paddlepaddle
- native_client/ctcdecode/LICENSE.parlance
- native_client/ctcdecode/Makefile
- native_client/ctcdecode/README.mozilla
- native_client/ctcdecode/__init__.py
- native_client/ctcdecode/ctc_beam_search_decoder.cpp
- native_client/ctcdecode/ctc_beam_search_decoder.h
- native_client/ctcdecode/decoder_utils.cpp
- native_client/ctcdecode/decoder_utils.h
- native_client/ctcdecode/numpy.i
- native_client/ctcdecode/output.h
- native_client/ctcdecode/setup.cfg
- native_client/ctcdecode/setup.py
- native_client/ctcdecode/swigwrapper.i
- native_client/deepspeech.cc
- util/feeding.py
- util/preprocess.py
- util/text.py
This doesn't yet remove libctc_decoder_with_kenlm.so and its users. Let's see if this PR passes tests.
> Expose ctcdecode to Python and use it in evaluate.py

- util/check_characters.py
- util/text.py
(1) added error message to text.py when the transcripts and alphabet.txt file dont match, and 
(2) a script to find the unique character set from the {train/dev/test} csv files
> Check for transcript & alphabet mis-match

- util/coordinator.py
> missing self argument

- util/preprocess.py
...the limitation to 8 threads looks a bit random to me.
> Preprocessing: use all available threads

- examples/mic_vad_streaming/README.md
- examples/mic_vad_streaming/mic_vad_streaming.py
- examples/mic_vad_streaming/requirements.txt
#1711
Think it all works, but could use someone to test, as I don't currently have a machine with both Linux and a working microphone.
> Add example for Python streaming from mic with VAD

- bin/import_swb.py
https://github.com/mozilla/DeepSpeech/issues/734
> changes to swb import

- util/check_characters.py
This way one can easily debug what file causes problems
> Character checking: be more verbose if something fails

- examples/ffmpeg_vad_streaming/README.MD
- examples/ffmpeg_vad_streaming/index.js
- examples/ffmpeg_vad_streaming/package.json
Tested with local file, RTMP and RTP source. Especially helpful to test real time inference scenarios.
> Add example for Nodejs streaming from arbitrary source with VAD and FFmpeg

- examples/mic_vad_streaming/README.md
add note for MacOS users how to install portaudio
> Update README for examples/mic_vad_streaming

- taskcluster/scriptworker-task-github.yml
- taskcluster/scriptworker-task-npm.yml
- taskcluster/scriptworker-task-pypi.yml
- taskcluster/simple-task.tyml
> Add missing upload_targets field

- taskcluster/darwin-opt-base.tyml
- taskcluster/linux-opt-base.tyml
> Move nc_asset_name to extra

- README.md
> Improve first user experience for CUDA deps

- tc-tests-utils.sh
- tc-train-tests.sh
- util/taskcluster.py
> Fetch ds_ctcdecoder from VERSION-based URL by default

- native_client/ctcdecode/path_trie.cpp
- native_client/ctcdecode/scorer.cpp
Something like this. Should be backwards compatible.
> Don't save/load trie for character based LMs (Fixes #1756)

- native_client/deepspeech.cc
> Pull tensors from TFLite model by name

- native_client/deepspeech.cc
- native_client/deepspeech.h
> Proper DeepSpeech error codes

- README.md
> Fixed #1864

- DeepSpeech.py
> Enable TFLite post-training quantization

- evaluate_tflite.py
- native_client/BUILD
- native_client/README.md
- native_client/deepspeech.h
- taskcluster/android-build.sh
> Add --define=runtime=tflite config_setting

- native_client/ctcdecode/ctc_beam_search_decoder.cpp
- native_client/ctcdecode/path_trie.cpp
- native_client/ctcdecode/path_trie.h
Uplifted from https://github.com/parlance/ctcdecode/commit/173dddbe3234420b174f6f2cf6b9855e26dc9bd3
> Record character timing offset at peak probability of character

- util/check_characters.py
> Force comments on output to allow piping

- bin/import_ts.py
see https://github.com/nicolaspanel/TrainingSpeech#last-releases--download for more info
> Use latest TS dataset

- README.md
- examples/net_framework/README.md
> Add Windows build doc

- examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs
The readkey is keeping DS process alive.
> Remove unnecessary read key

- examples/net_framework/CSharpExamples/CSharpExamples.sln
- examples/net_framework/CSharpExamples/DeepSpeechClient/DeepSpeech.cs
- examples/net_framework/CSharpExamples/DeepSpeechClient/Interfaces/IDeepSpeech.cs
- examples/net_framework/CSharpExamples/DeepSpeechConsole/Program.cs
- examples/net_framework/CSharpExamples/DeepSpeechWPF/MainWindow.xaml.cs
Removed unused build configurations to avoid: https://discourse.mozilla.org/t/compiling-for-windows/32939/64
Added the missing doc of the interface, and chanaged the interface to be disposable.
@lissyx  or @reuben please review :)
> Remove unused configurations and add interface docs

- DeepSpeech.py
Usage: `$ CUDA_VISIBLE_DEVICES="" python DeepSpeech.py --notrain --notest --export_dir /path/to/models/ --checkpoint_dir /path/to/checkpoints/ --n_steps -1 --export_batch_size -1`
from client side:
```
tf_logits = session.graph.get_tensor_by_name('import/logits:0')
tf_input_node = session.graph.get_tensor_by_name('import/input_node:0')
tf_input_lengths = session.graph.get_tensor_by_name('import/input_lengths:0')
logits = tf_session.run(tf_logits, feed_dict={
tf_input_node: pad_to_dense(windows),
tf_input_lengths: features_lengths,
})
```
> enable dynamic batch size through --export_batch_size -1 (see #1923)

- tc-tests-utils.sh
Can't replicate on my local setup, need to see the cluster result.
> Move NuGet builds to avoid triggered clean

- examples/mic_vad_streaming/mic_vad_streaming.py
Hi deepseech mods!
I have added scipy to this module for signal resampling. 
It has been tested and seems to work better than ever.
If the microphone rate is the same as the network, (16000) no resampling necessary.
Happy to make any modifications if suggested.
cheers,
Jordan
> Feature/resample examples mic vad streaming input rate 

- README.md
change mentions of `import_cv.py` --> `import_cv2.py`
> import_cv2

- taskcluster/scriptworker-task-github.yml
- taskcluster/scriptworker-task-pypi.yml
> Add Windows Python packages to upload tasks

- .taskcluster.yml
- tc-schedule.sh
NetworkX upgrade has no more support for Python 3.4
Fixes #2045
> Upgrade system for Python 3.5 for decision task

- native_client/client.cc
Changes CSV output to JSON and exposes transcription probability.
> Change CSV output to JSON

- native_client/args.h
- native_client/client.cc
- native_client/dotnet/DeepSpeech.sln
- native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/DeepSpeechClient.csproj
- native_client/dotnet/DeepSpeechClient/Extensions/NativeExtensions.cs
- native_client/dotnet/DeepSpeechClient/Interfaces/IDeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/Models/Metadata.cs
- native_client/dotnet/DeepSpeechClient/Models/MetadataItem.cs
- native_client/dotnet/DeepSpeechClient/NativeImp.cs
- native_client/dotnet/DeepSpeechClient/Structs/Metadata.cs
- native_client/dotnet/DeepSpeechClient/Structs/MetadataItem.cs
- native_client/dotnet/DeepSpeechConsole/DeepSpeechConsole.csproj
- native_client/dotnet/DeepSpeechConsole/Program.cs
- native_client/java/jni/deepspeech.i
- native_client/java/libdeepspeech/src/androidTest/java/org/mozilla/deepspeech/libdeepspeech/test/BasicTest.java
- native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java
- native_client/javascript/client.js
- native_client/javascript/deepspeech.i
- native_client/javascript/index.js
- native_client/python/__init__.py
- native_client/python/client.py
- native_client/python/impl.i
- tc-tests-utils.sh
> Expose extended metadata information to bindings

- bin/import_lingua_libre.py
> LinguaLibre importer

- bin/run-ldc93s1.sh
- bin/run-tc-ldc93s1_checkpoint.sh
- bin/run-tc-ldc93s1_new.sh
- bin/run-tc-ldc93s1_singleshotinference.sh
- bin/run-tc-ldc93s1_tflite.sh
> Force only one GPU on LDC93S1 scripts

- README.md
> Bring back CUDA and CuDNN versions.

- bin/import_ts.py
> Update TrainingSpeech dataset

- bin/import_ts.py
> Ensure TrainingSpeech is properly formatted

- native_client/deepspeech.cc
> Move init of previous_state_{c,h}

- bin/import_lingua_libre.py
> Do not import known bogus Lingua Libre records

- bin/import_cv2.py
> Ensure frames counter is initialized

- bin/import_lingua_libre.py
- bin/import_ts.py
> Frame counter should be initialized on all importers

- tc-tests-utils.sh
> Update ElectronJS headers dist-url

- native_client/ds_git_version.sh
> Handle git submodules for getting DeepSpeech / TensorFlow versions

- taskcluster/tc-tests-utils.sh
> Package DeepSpeech header

- bin/import_aidatatang.py
- bin/import_freestmandarin.py
- bin/import_primewords.py
Would be interesting to see if we could get a license to the full DataTang corpus of 1505 hours: https://en.datatang.com/en/opensource
> More mandarin importers

- README.md
> Document TF_FORCE_GPU_ALLOW_GROWTH

- util/taskcluster.py
Signed-off-by: Li Li <eggonlea@msn.com>
> Fix trivial shadow variable in util script

- native_client/python/client.py
Abstract SAMPLE_RATE variable for use with other formats such as 8000hz
I understand default beam width to now be 1024
> Abstract sample rate / update beam width

- bin/import_librivox.py
Sets output format to Sox transformer
> Allow for different sample rate exports

- native_client/ctcdecode/ctc_beam_search_decoder.cpp
> Ensure proper removal of prefix

- taskcluster/cuda-build.sh
> Ensure --cuda flag passed for CUDA builds

- DeepSpeech.py
- evaluate.py
- util/config.py
- util/flags.py
This reverts commit dc78f8d1e65c4b387aa335df243898cd04704f98.
> Revert "Remove deprecated SessionConfig" as it inadvertently disables soft placement of ops

- README.md
- data/README.md
Fixed the commits. sorry for the trouble.
> Added reference about generate_trie for clarity

- native_client/java/README.md
> Fix typo in Android doc

- taskcluster/.shared.yml
> Add liblzma-dev to build python from pyenv with _lzma

- native_client/Makefile
> Remove useless make target 'bindings-clean'

- DeepSpeech.py
Avoid needing to use the same batch size for training and validation.
> Use dynamic batch size in train/val graph

- DeepSpeech.py
- adds similar checkpoint load mechanism for transfer learning as in master
> Allow continuing transfer learning

- examples/ffmpeg_vad_streaming/index.js
- examples/net_framework/DeepSpeechWPF/MainWindow.xaml.cs
- native_client/client.cc
- native_client/deepspeech.cc
- native_client/deepspeech.h
- native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/Interfaces/IDeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/NativeImp.cs
- native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java
- native_client/python/__init__.py
> Remove ununsed prealloc frames

- taskcluster/.shared.yml
- taskcluster/win-opt-base.tyml
Here's hoping this doesn't completely explode.
> Use globbing instead of hardcoding SWIG version

- DeepSpeech.py
- bin/graphdef_binary_to_text.py
- bin/ops_in_graph.py
- evaluate.py
- util/config.py
- util/feeding.py
This shouldn't break any tests.
> Run tf_upgrade_v2 to ease eventual transition to TF 2.0

- evaluate_tflite.py
- examples/net_framework/DeepSpeechWPF/MainWindow.xaml.cs
- native_client/client.cc
- native_client/deepspeech.cc
- native_client/deepspeech.h
- native_client/deepspeech_compat.h
- native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/Interfaces/IDeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/NativeImp.cs
- native_client/dotnet/DeepSpeechClient/Structs/ModelState.cs
- native_client/dotnet/DeepSpeechConsole/Program.cs
- native_client/java/app/src/main/java/org/mozilla/deepspeech/DeepSpeechActivity.java
- native_client/java/libdeepspeech/src/androidTest/java/org/mozilla/deepspeech/libdeepspeech/test/BasicTest.java
- native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java
- native_client/javascript/client.js
- native_client/javascript/deepspeech.i
- native_client/javascript/index.js
- native_client/modelstate.cc
- native_client/modelstate.h
- native_client/python/__init__.py
- native_client/python/client.py
- native_client/python/impl.i
- native_client/test/concurrent_streams.py
- native_client/tflitemodelstate.cc
- native_client/tflitemodelstate.h
- native_client/tfmodelstate.cc
- native_client/tfmodelstate.h
Removed unused params, made naming more consistent.
> [BREAKING] API cleanup

- examples/ffmpeg_vad_streaming/index.js
- examples/ffmpeg_vad_streaming/package.json
- examples/ffmpeg_vad_streaming/test.sh
- examples/mic_vad_streaming/mic_vad_streaming.py
- examples/mic_vad_streaming/requirements.txt
- examples/mic_vad_streaming/test.sh
- examples/nodejs_wav/index.js
- examples/nodejs_wav/package.json
- examples/nodejs_wav/test.sh
- examples/tests.sh
- examples/vad_transcriber/audioTranscript_cmd.py
- examples/vad_transcriber/audioTranscript_gui.py
- examples/vad_transcriber/requirements.txt
- examples/vad_transcriber/test.sh
- examples/vad_transcriber/wavTranscriber.py
- taskcluster/examples-base.tyml
- taskcluster/examples-ffmpeg_vad_streaming-node10.yml
- taskcluster/examples-ffmpeg_vad_streaming-node8.yml
- taskcluster/examples-mic_vad_streaming-py36.yml
- taskcluster/examples-mic_vad_streaming-py37.yml
- taskcluster/examples-nodejs_wav-node10.yml
- taskcluster/examples-nodejs_wav-node8.yml
- taskcluster/examples-vad_transcriber-py35.yml
- taskcluster/examples-vad_transcriber-py36.yml
- taskcluster/examples-vad_transcriber-py37.yml
> Run examples on TaskCluster

- README.md
Updated README with augmentation documentation. 
Usage of augmentation
> Augmentation Documentation

- README.md
> Put back ReadTheDocs badge

- native_client/ctcdecode/scorer.cpp
> Load KenLM with LAZY

- native_client/deepspeech.cc
> Fixing typo s/StreamingContext/StreamingState/

- DeepSpeech.py
- util/feeding.py
> Disable cache when data augmentation is set

- util/taskcluster.py
> Move default branch to current VERSION content instead of master

- DeepSpeech.py
> Use TFLite optimizations flag

- README.rst
- TRAINING.rst
- USING.rst
- native_client/README.rst
- native_client/java/README.rst
- native_client/python/setup.cfg
> Fix broken references to README.md

- bin/import_m-ailabs.py
fixing issue found in https://github.com/MozillaItalia/DeepSpeech-Italian-Model/pull/21
> Setted default param of skiplist to ''

- doc/C-API.rst
> Add missing doc for new API

- native_client/tfmodelstate.cc
> Update doc link for model compatibility

- DeepSpeech.py
- util/flags.py
Automatic Mixed Precision (AMP) training on GPU for TensorFlow has been recently introduced:
https://medium.com/tensorflow/automatic-mixed-precision-in-tensorflow-for-faster-ai-training-on-nvidia-gpus-6033234b2540
Automatic mixed precision training makes use of both FP32 and FP16 precisions where appropriate. FP16 operations can leverage the Tensor cores on NVIDIA GPUs (Volta, Turing or newer architectures) for improved throughput. Mixed precision training also often allows larger batch sizes.
This PR adds GPU automatic mixed precision training to `DeepSpeech` via passing the flags value `--auto_mixed_precision=True`.
```
./DeepSpeech.py --train_files ./train.csv --dev_files ./dev.csv --test_files ./test.csv --automatic_mixed_precision
```
On a Volta generation V100 GPU, automatic mixed …
> Adding GPU automatic mixed precision training

- native_client/ctcdecode/Makefile
- native_client/ctcdecode/build_common.py
- native_client/ctcdecode/path_trie.cpp
- native_client/ctcdecode/path_trie.h
- native_client/trie_load.cc
These are helpful when diagnosing problems with the decoder.
> Add some debugging helpers behind a preprocessor flag

- native_client/ctcdecode/ctc_beam_search_decoder.cpp
- native_client/ctcdecode/path_trie.cpp
- native_client/ctcdecode/path_trie.h
> Use std::shared_ptr instead of raw pointer for dictionary_

- evaluate.py
@lissyx I think this is the cause of the problem you mentioned on IRC.
> Avoid using references to the same object in sparse_tuple_to_text

- DeepSpeech.py
- evaluate.py
- native_client/ctcdecode/ctc_beam_search_decoder.cpp
- native_client/ctcdecode/scorer.cpp
I'm in the process of cleaning up the decoder UTF-8 mode code for merging, and these are some general fixes from that branch that apply outside of just the context of UTF-8 and can be taken out of that branch. I've tested that they don't negatively affect our WER (in fact they improve it marginally).
> Uplift general fixes from UTF-8 work

- bin/import_tuda.py
> TUDA importer

- examples/mic_vad_streaming/requirements.txt
- native_client/ctcdecode/Makefile
- native_client/python/Makefile
- native_client/python/__init__.py
- native_client/swig_py38_untrack.patch
- taskcluster/.shared.yml
- taskcluster/examples-mic_vad_streaming-py38.yml.DISABLED_UNTIL_SCIPY_PY38
- taskcluster/examples-vad_transcriber-py38.yml
- taskcluster/tc-tests-utils.sh
- taskcluster/test-python_38-darwin-amd64-opt.yml
- taskcluster/test-python_38-linux-amd64-opt.yml
- taskcluster/test-python_38-linux-amd64-prod_pbmodel-opt.yml
- taskcluster/test-python_38-win-amd64-opt.yml
- taskcluster/win-build.sh
> Build Python 3.8 wheels

- TRAINING.rst
To reflect new functionality in https://github.com/mozilla/DeepSpeech/pull/2434
> adding amp doc

- bin/import_cv2.py
> Making sample paths relative; additional sub-sets

- bin/import_m-ailabs.py
> Fix for empty skip list case; making linter happy

- bin/import_m-ailabs.py
> Relative paths in M-AILAB importer

- native_client/swig_node_v12_0001-Upgrade-SWIG-to-support-NodeJS-v12-V8-v7.6-v8-v7.8-r.patch
- taskcluster/.shared.yml
- taskcluster/darwin-opt-base.tyml
- taskcluster/tc-tests-utils.sh
- taskcluster/test-electronjs_v7.0-darwin-amd64-opt.yml
- taskcluster/test-electronjs_v7.0-linux-amd64-opt.yml
- taskcluster/test-electronjs_v7.0-win-amd64-opt.yml
> Add ElectronJS v7.0

- bin/import_swc.py
- bin/import_tuda.py
> Fix: ms per char minimum for SWC and TUDA importers

- README.rst
Show examples on the first page, so people can easily find them.
> Add links to examples to README.rst

- examples/vad_transcriber/wavTranscription.md
The tutorial misses a few steps for the setup and doesn't mention a few common errors.
I also tried to format it better.
> Better instructions for example/vad_transcriber

- examples/README.rst
Give a short description and overview of the content of the folder, so we can link from the main README.rst
> Add README.rst to example Folder

- native_client/python/client.py
Modified client.py to add function for converting metadata to timestamp of each word
> Added support of --json timestamp in python client.py

- native_client/python/client.py
Fixed `store_true` in `--json` in client,py. Issue #2545
> Fixed store_true in --json

- README.rst
- examples/README.rst
> Link to proper README for examples/

- DeepSpeech.py
- util/feeding.py
This causes weird behavior on our cluster, uses a lot of memory, and is much slower than caching to disk.
> Disable caching features to memory

- native_client/README.rst
the ticks messed up the linking
> remove bad ticks

- native_client/deepspeech.h
- native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/Interfaces/IDeepSpeech.cs
- native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java
- native_client/javascript/index.js
- native_client/python/__init__.py
> Remove outdated mention of DS_IntermediateDecode being expensive to call

- doc/DotNet-API.rst
- examples/net_framework/DeepSpeechWPF/App.xaml.cs
- examples/net_framework/DeepSpeechWPF/ViewModels/MainWindowViewModel.cs
- native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/DeepSpeechClient.csproj
- native_client/dotnet/DeepSpeechClient/Interfaces/IDeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/Models/DeepSpeechStream.cs
- native_client/dotnet/DeepSpeechClient/NativeImp.cs
- native_client/dotnet/DeepSpeechConsole/Program.cs
Most of the test passing but I still need to test this with a prod model. The streaming test sometimes returns weird words at the beginning and at the end, I guess it is the extra data that the dummy model fails to recognize as silence.
At the moment I can't train a prod model to test and discard the silence issue.
> Multi-stream support .NET

- USING.rst
Hey, I just implemented DeepSpeech's bindings in Vlang and wanted to add it into the 3rd Party Bindings list.
> Added third-party bindings for Vlang

- taskcluster/scriptworker-task-pypi.yml
> Also upload Windows TFLite Python package to PyPI

- DeepSpeech.py
> Set forget_bias=0 for static RNN implementation

- TRAINING.rst
> TRAINING.rst - Include exact command for getting mmap tool

- bin/import_swc.py
> Implements #2624 - SWC importer: CSV columns for article and speaker

- native_client/ctcdecode/ctc_beam_search_decoder.cpp
> Don't OOV_SCORE on empty prefix

- taskcluster/tc-cpp_tflite-tests-prod.sh
- taskcluster/tc-node_tflite-tests-prod.sh
- taskcluster/tc-python_tflite-tests-prod.sh
- taskcluster/tc-tests-utils.sh
- taskcluster/test-cpp_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_10x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_11x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_12x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_13x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_4x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_5x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_6x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_7x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_8x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-nodejs_9x_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-python_27m_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-python_27mu_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-python_35_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-python_36_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-python_37_tflite-linux-amd64-prod-opt.yml
- taskcluster/test-python_38_tflite-linux-amd64-prod-opt.yml
> Add TFLite prod tests

- util/spectrogram_augmentations.py
As #2560 mentioned, fix augmentation axis inversion problem
> fix axis inversion problem

- USING.rst
> Ensure document vc_redist

- README.rst
- doc/DeepSpeech.rst
- doc/TRAINING.rst
- doc/USING.rst
- doc/conf.py
- doc/index.rst
- native_client/tflitemodelstate.cc
- native_client/tfmodelstate.cc
> Publish README/USING/TRAINING to readthedocs

- util/flags.py
My understanding is that the sample database format will supercede feature caching, but in the mean time here's an improvement for the help text.
> Improve --feature_cache help text (Fixes #1709)

- native_client/java/libdeepspeech/src/androidTest/java/org/mozilla/deepspeech/libdeepspeech/test/BasicTest.java
- native_client/java/libdeepspeech/src/main/java/org/mozilla/deepspeech/libdeepspeech/DeepSpeechModel.java
> Fix DS_EnableDecoderWithLM typo in Android bindings

- native_client/client.cc
- native_client/python/client.py
> Fix word detection for time computation

- doc/TRAINING.rst
> Ensure documentation mentions python3-dev

- native_client/dotnet/DeepSpeechClient/DeepSpeech.cs
- native_client/dotnet/DeepSpeechClient/NativeImp.cs
> Fix Intermediate decoding 

- SUPPORT.rst
- native_client/CODINGSTYLE.md
> Point people to Matrix room instead of IRC

- bin/import_ts.py
> Use other storage for TrainingSpeech dataset

- doc/USING.rst
- native_client/README.rst
> Remove references to generate_trie from docs (Fixes #2761)

- taskcluster/.shared.yml
- taskcluster/tc-all-vars.sh
- taskcluster/test-electronjs_v8.0-darwin-amd64-opt.yml
- taskcluster/test-electronjs_v8.0-win-amd64-opt.yml
- taskcluster/test-electronjs_v8.0_16k-linux-amd64-opt.yml
- taskcluster/test-electronjs_v8.0_8k-linux-amd64-opt.yml
> Support ElectronJS v8.0

- util/taskcluster.py
> Automagically decompress GZipped artifacts

- DeepSpeech.py
- taskcluster/tc-train-tests.sh
- util/checkpoints.py
- util/flags.py
Continuing from PR #2742 by @DanBmh to make sure TaskCluster tests are passing.
> Reduce learning rate on plateau

- transcribe.py
Replaced non existing try_loading() method with the load_or_init_graph() method and respect load flag
Removed tf.train.Saver()
> Fix transcribe.py - use new checkpoint load method

- taskcluster/scriptworker-task-github.yml
Added the ctc decoder builds tasks in the python list of the github upload task.
Fixes #2717
> added ctc decoder builds tasks

- doc/USING.rst
> Doc: change cuDNN dependency to 7.6

- util/feeding.py
> Ensure sample rate comparison with proper types

- taskcluster/tc-asserts.sh
- taskcluster/tc-cppwin-ds-tests.sh
- taskcluster/tc-electron-tests.sh
- taskcluster/tc-netframework-ds-tests.sh
- taskcluster/tc-node-tests.sh
- taskcluster/tc-node-utils.sh
- taskcluster/tc-python-tests.sh
- taskcluster/test-cpp_16k-win-cuda-opt.yml
- taskcluster/test-electronjs_v8.0_multiarchpkg-win-amd64-opt.yml
- taskcluster/test-electronjs_v8.0_multiarchpkg-win-cuda-opt.yml
- taskcluster/test-electronjs_v8.0_multiarchpkg-win-tflite-opt.yml.disabled
- taskcluster/test-netframework-win-cuda-opt.yml
- taskcluster/test-nodejs_13x_multiarchpkg-win-cuda-opt.yml
- taskcluster/test-python_35-win-cuda-opt.yml
- taskcluster/test-python_36-win-cuda-opt.yml
- taskcluster/test-python_37-win-cuda-opt.yml
- taskcluster/test-python_38-win-cuda-opt.yml
- taskcluster/test-win-cuda-opt-base.tyml
- taskcluster/worker.cyml
> Add Windows CUDA CI

- requirements.txt
Fixes security issues in TensorFlow and stops GitHub nagging us.
> Bump dependency to TensorFlow 1.15.2

- bin/build_sdb.py
- bin/play.py
- util/audio.py
- util/feeding.py
- util/sample_collections.py
Plus a bit of documentation alignment and extension following the NumPy docstring style.
> Fix #2830 - Support for unlabeled samples

- .compute
> Updated .compute

- training/deepspeech_training/train.py
> Add some early checks, for Scorer at first

- doc/TRAINING.rst
> Mention validate_label_locale in training doc

- doc/TRAINING.rst
> Transfer Learning docs

- bin/import_lingua_libre.py
This gets rid of some assertion errors, at least with the Polish dataset
> import_lingua_libre.py: n channels + bitdepth

- bin/import_m-ailabs.py
> M-AILAB importer: Ensure all samples are 16 kHz

- evaluate_tflite.py
Bug fix to missing external scorer handling in evaluate_tflite.py
> Add missing external scorer

- native_client/README.rst
ref https://github.com/mozilla/DeepSpeech/issues/2943
> Doc: Mention we explicitely need Bazel 0.24.1

- native_client/Makefile
> Install deepspeech header

- data/lm/generate_lm.py
Error message is:
```
kenlm/lm/builder/adjust_counts.cc:60 in void lm::builder::{anonymous}::StatCollector::CalculateDiscounts(const lm::builder::DiscountConfig&) threw BadDiscountException because `discounts_[i].amount[j] < 0.0 || discounts_[i].amount[j] > j'.
ERROR: 1-gram discount out of range for adjusted count 3: -0.20000005
```
This fix is given in kenlm issue tracker, when small dataset are used.
> fix building ARPA file (building_lm using kenlm)

- bin/import_cv2.py
Writes additional `train-all.csv` with all validated samples except speakers and/or transcripts already in dev or test.
> CV2 importer: train-all.csv

- taskcluster/scriptworker-task-readthedocs.yaml
Corresponding scriptworker changes at https://github.com/mozilla/deepspeech-pkguploadworker/compare/1e4ef28e463cd17f5298278d445020a78f2864af...ad10a9019f2e45751da419290c9dd16546c9f7a1
> Add task to trigger ReadTheDocs builds & version update

- .travis.yml
- taskcluster/tc-train-unittests.sh
- taskcluster/test-training-unittests_8k-linux-amd64-py35m-opt.yml
- taskcluster/test-training-unittests_8k-linux-amd64-py36m-opt.yml
- taskcluster/test-training-unittests_8k-linux-amd64-py37m-opt.yml
> Move unit tests to TaskCluster

- training/deepspeech_training/evaluate.py
- training/deepspeech_training/util/feeding.py
Stop doing incomplete validation and test epochs.
> Only use drop_remainder in dataset for train phase

- bin/import_cv.py
- bin/import_cv2.py
- bin/import_lingua_libre.py
- bin/import_m-ailabs.py
- bin/import_slr57.py
- bin/import_swc.py
- bin/import_ts.py
- bin/import_tuda.py
https://docs.python.org/3/library/csv.html#csv.writer
> Fix csv writer parameter

- bin/run-tc-ldc93s1_new_metrics.sh
- taskcluster/tc-train-extra-tests.sh
- taskcluster/test-training-extra_16k-linux-amd64-py35m-opt.yml
- taskcluster/test-training-extra_16k-linux-amd64-py36m-opt.yml
- taskcluster/test-training-extra_16k-linux-amd64-py37m-opt.yml
- taskcluster/test-training-extra_8k-linux-amd64-py36m-opt.yml
- taskcluster/test-training-extra_8k-linux-amd64-py37m-opt.yml
- taskcluster/test-training_16k-linux-amd64-py35m-opt.yml
- taskcluster/test-training_16k-linux-amd64-py36m-opt.yml
- taskcluster/test-training_16k-linux-amd64-py37m-opt.yml
- taskcluster/test-training_8k-linux-amd64-py36m-opt.yml
- taskcluster/test-training_8k-linux-amd64-py37m-opt.yml
- training/deepspeech_training/train.py
- training/deepspeech_training/util/flags.py
For now just a way to look at extra validation sets without affecting best validation loss.
> Add read-only metrics tracking

- bin/import_cv2.py
- bin/import_lingua_libre.py
- bin/import_m-ailabs.py
- bin/import_slr57.py
- bin/import_swc.py
- bin/import_tuda.py
> Fix: #3130 - Missing deepspeech_training.util.text.Alphabet

- bin/build_sdb.py
> Resolves #3144 - Add augmentation support to build_sdb.py

- bin/import_swc.py
- bin/import_tuda.py
> Use ElementTree instead of deprecated cElementTree.

- native_client/generate_scorer_package.cpp
> Fix alphabet logic in generate_scorer_package.

- doc/TRAINING.rst
Adds the detailed information about the expected CSV files structure.
> Extend docu about the CSV files

- taskcluster/tf_android-arm64-opt.yml
- taskcluster/tf_android-armv7-opt.yml
- taskcluster/tf_darwin-amd64-opt.yml
- taskcluster/tf_linux-amd64-cpu-opt.yml
- taskcluster/tf_linux-amd64-gpu-opt.yml
- taskcluster/tf_linux-arm64-cpu-opt.yml
- taskcluster/tf_linux-rpi3-cpu-opt.yml
- taskcluster/tf_tc-build.sh
- taskcluster/tf_tc-setup.sh
- taskcluster/tf_win-amd64-cpu-opt.yml
- taskcluster/tf_win-amd64-gpu-opt.yml
> Decouple builds

- training/deepspeech_training/train.py
Improve readability.
Split to separate pr from #3268.
> Refactor rlrop condition

- CONTRIBUTING.rst
First start to flesh out more elaborate contribution guidelines + best practices
> Docs contributing

- doc/TRAINING.rst
As more and more people simply clone the master branch, maybe this steers them towards using a released branch.
> Trying to get fewer master branch training errors

- doc/C-API.rst
> Fix missing doc for new Hot Word API

- training/deepspeech_training/util/audio.py
> mono-channel error, not just an assertion

- README.rst
- <small>***fixing minor issues with readme.rst***</small>
> [docs/typos/enhance] - mozilla/deepspeech/readme.rst - update

- native_client/python/__init__.py
Already applied to master applying to r0.9 as requested
> Tiny fix to addHotWord doc string parameters

- bin/import_voxforge.py
> Add missing sys import to import_voxforge.py

- README.rst
> Use HTTPS in README.md

- training/deepspeech_training/train.py
Half question & half PR, but if I follow the code correctly, these `outputs['outputs']` are already softmax'ed, so they're probs, not logits, yes? This tripped me up as I sat here double-softmaxing and washing out my probabilities for a little while.
> Minor Training Variable Consistency fix

- native_client/java/libdeepspeech/src/androidTest/java/org/mozilla/deepspeech/libdeepspeech/test/BasicTest.java
Refer to the Issue #3336 
Running HotWord test on Java client with some Hardcoded words and their boost values.
> Run test On Java Client

- bin/import_ccpmf.py
- training/deepspeech_training/util/downloader.py
Released by Ministère de l'Economie, des Finances, et de la Relance
> Importer for dataset from Centre de Conférences Pierre Mendès-France

- doc/TRAINING.rst
I'm using this documentation to build out a Playbook - please don't interpret this as nitpicking, saw a minor change and made it.
> Update refs to 0.9.3 from 0.9.2

- training/deepspeech_training/util/io.py
> Replace `remove_remote()` method with `remove` method

- training/deepspeech_training/util/check_characters.py
> Fix documentation for check_characters.py script

- bin/import_m-ailabs.py
The M-AILABS link was broken, I replaced it with the one that I found on the same website in the download page:
http://www.caito.de/2019/01/the-m-ailabs-speech-dataset/
> Fix M-AILABS broken link
